sunshine_name = FX99
address_family = ipv4
bind_address = 192.168.12.220
upnp = disabled
origin_web_ui_allowed = lan
lan_encryption_mode = 2
wan_encryption_mode = 2

stream_audio = disabled
encoder = nvenc
capture = nvfbc
hevc_mode = 0
av1_mode = 1
nvenc_preset = 1
nvenc_twopass = quarter_res
max_bitrate = 40000
minimum_fps_target = 30

file_apps = /home/derek/.config/sunshine/apps.json
log_path = /home/derek/.local/state/fx99-sunshine.log
