section: screens
	omen:
	am4:
end

section: links
	omen:
		right = am4
	am4:
		left = omen
end

section: options
	protocol = barrier
	relativeMouseMoves = true
	win32KeepForeground = false
	defaultLockToScreenState = false
	disableLockToScreen = false
	clipboardSharing = true
	clipboardSharingSize = 65536
	switchCorners = none
	switchCornerSize = 0
end
