#!/usr/bin/env python3
"""sizing_map — every context / KV / output / attempt / deadline number on this host, in one table,
with the invariants that tie them together.

The seat is the fact (vLLM's max_model_len, KV pool, max_num_seqs). backends-linux.toml declares
what the seat can serve; everything else derives from it. This tool reads all of those places,
prints them as one table, and checks the derivation rules, so docs/sizing-map.md cannot drift
from the files it describes.

    python tools/ops/sizing_map.py --check          exit 1 and name every violated invariant
    python tools/ops/sizing_map.py --json           the rows (sizing-map.v1), sorted, no clock
    python tools/ops/sizing_map.py --render         rewrite the generated block in docs/sizing-map.md (reads the live seats)
    python tools/ops/sizing_map.py --live           also read the running seats (/v1/models, /metrics)

Byte-stable: no timestamps, sorted rows, live values only when asked. Never prints a secret: the
seat key is read into the process for the two HTTP calls and nothing else.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tomllib
import urllib.request
from pathlib import Path
from typing import Any, Callable, Optional

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
HOME = Path.home()
PROD = Path(os.environ.get("HEARTH_ROOT", str(HOME / "hearth-production")))
DOC = REPO / "docs" / "sizing-map.md"
BEGIN, END = "<!-- sizing-map:begin (generated by tools/ops/sizing_map.py; do not hand-edit) -->", "<!-- sizing-map:end -->"

Row = dict[str, Any]


def row(layer: str, setting: str, value: Any, source: str, consumer: str, bounds: str, note: str = "") -> Row:
    return {"layer": layer, "setting": setting, "value": value, "source": source, "consumer": consumer,
            "bounds": bounds, "note": note}


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
    except OSError:
        return ""


def _grep(text: str, pattern: str, group: int = 1, cast: Callable = str, default=None):
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        return default
    try:
        return cast(m.group(group))
    except (TypeError, ValueError):
        return default


def _line_of(path: Path, pattern: str) -> str:
    text = _read(path)
    for i, line in enumerate(text.splitlines(), 1):
        if re.search(pattern, line):
            return f"{_rel(path)}:{i}"
    return _rel(path)


def _rel(path: Path) -> str:
    p = str(path)
    for base, name in ((str(REPO), "repo"), (str(HOME), "~")):
        if p.startswith(base):
            return name + p[len(base):]
    return p


# --- collectors -------------------------------------------------------------------------------

def collect_seats(live: bool) -> list[Row]:
    rows: list[Row] = []
    script = HOME / "bin" / "start-vllm-seat.sh"
    stext = _read(script)
    defaults = {"OMEN_MAX_MODEL_LEN": _grep(stext, r"OMEN_MAX_MODEL_LEN:-(\d+)", cast=int, default=16384),
                "OMEN_MAX_NUM_SEQS": _grep(stext, r"OMEN_MAX_NUM_SEQS:-(\d+)", cast=int, default=16),
                "OMEN_GPU_MEM_UTIL": _grep(stext, r"OMEN_GPU_MEM_UTIL:-([0-9.]+)", cast=float, default=0.82)}
    for k, v in defaults.items():
        rows.append(row("seat", f"script default {k}", v, _line_of(script, k + ":-"), "vLLM (any seat without a drop-in)",
                        "context / sequences / VRAM fraction", "applies when no drop-in sets it"))
    key = None
    if live:
        for line in _read(HOME / ".config" / "omen-vllm" / "omen-api.env").splitlines():
            if line.startswith("VLLM_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"')
    for seat in (0, 1):
        unit = f"omen-vllm@{seat}"
        try:
            env = subprocess.run(["systemctl", "--user", "show", unit, "-p", "Environment", "--value"],
                                 capture_output=True, text=True, timeout=10).stdout.split()
        except (OSError, subprocess.TimeoutExpired):
            env = []
        eff = {}
        for item in env:
            if item.startswith("OMEN_") and "=" in item and not re.search(r"(?:TOKEN|KEY|SECRET)$", item.partition("=")[0], re.I):   # credentials end in TOKEN/KEY; OMEN_MAX_BATCHED_TOKENS is a size
                k, _, v = item.partition("="); eff[k] = v
        dropins = sorted(p.name for p in (HOME / ".config" / "systemd" / "user" / f"{unit}.service.d").glob("*.conf"))
        src = f"~/.config/systemd/user/{unit}.service.d/{{{','.join(dropins)}}}"
        served = eff.get("OMEN_SERVED_NAME") or (Path(eff["OMEN_MODEL"]).name + " (served name = checkpoint dir)" if eff.get("OMEN_MODEL") else "")
        rows.append(row("seat", f"{unit} served model", served, src, f"HAProxy :{18091 + seat}", "which checkpoint answers"))
        mml = int(eff.get("OMEN_MAX_MODEL_LEN") or defaults["OMEN_MAX_MODEL_LEN"])
        rows.append(row("seat", f"{unit} max_model_len", mml, src, "vLLM", "input + output tokens per request"))
        seqs = int(eff.get("OMEN_MAX_NUM_SEQS") or defaults["OMEN_MAX_NUM_SEQS"])
        rows.append(row("seat", f"{unit} max_num_seqs", seqs, src if eff.get("OMEN_MAX_NUM_SEQS") else _line_of(script, "OMEN_MAX_NUM_SEQS:-"),
                        "vLLM scheduler", "concurrent sequences admitted", "" if eff.get("OMEN_MAX_NUM_SEQS") else "script default; no drop-in sets it"))
        rows.append(row("seat", f"{unit} gpu_memory_utilization", float(eff.get("OMEN_GPU_MEM_UTIL") or defaults["OMEN_GPU_MEM_UTIL"]), src, "vLLM", "VRAM fraction (weights + KV)"))
        if eff.get("OMEN_KV_CACHE_BYTES"):
            rows.append(row("seat", f"{unit} kv_cache_memory_bytes", int(eff["OMEN_KV_CACHE_BYTES"]), src, "vLLM", "fixed KV pool (overrides the utilisation for KV)"))
        rows.append(row("seat", f"{unit} attention_backend", eff.get("OMEN_ATTN_BACKEND") or "TRITON_ATTN", src if eff.get("OMEN_ATTN_BACKEND") else _line_of(script, "OMEN_ATTN_BACKEND:-"),
                        "vLLM", "attention kernel (prefill and decode rate at depth)", "" if eff.get("OMEN_ATTN_BACKEND") else "script default; no drop-in sets it"))
        for k, label in (("OMEN_MAX_BATCHED_TOKENS", "max_num_batched_tokens"), ("OMEN_PREFIX_MATCH_UNIT", "prefix_match_unit"), ("OMEN_MTP_K", "mtp_k")):
            if eff.get(k):
                rows.append(row("seat", f"{unit} {label}", int(eff[k]), src, "vLLM", {"max_num_batched_tokens": "prefill chunk", "prefix_match_unit": "prefix-hit granularity", "mtp_k": "speculative tokens"}[label]))
        # stale-comment and duplicate-key detectors on the drop-ins
        setters: dict[str, list[str]] = {}
        for name in dropins:
            text = _read(HOME / ".config" / "systemd" / "user" / f"{unit}.service.d" / name)
            for k in re.findall(r'^Environment="?(OMEN_[A-Z_]+)=', text, re.M):
                setters.setdefault(k, []).append(name)
            if re.search(r"staged", text, re.I) and name.endswith(".conf"):
                rows.append(row("seat", f"{unit} {name} says 'staged'", True, f"~/.config/systemd/user/{unit}.service.d/{name}", "operator", "misleading comment on an ACTIVE drop-in"))
        for k, names in sorted(setters.items()):
            if len(names) > 1:
                rows.append(row("seat", f"{unit} {k} set by {len(names)} drop-ins", " < ".join(names), f"~/.config/systemd/user/{unit}.service.d/", "systemd (last wins, alphabetical)", "the earlier file is dead configuration"))
        if live and key:
            try:
                req = urllib.request.Request(f"http://127.0.0.1:{18091 + seat}/v1/models", headers={"Authorization": f"Bearer {key}"})
                with urllib.request.urlopen(req, timeout=5) as r:
                    data = json.load(r)["data"]
                for m in data:
                    rows.append(row("seat-live", f"{unit} /v1/models", f"{m['id']} max_model_len={m.get('max_model_len')}", f"http://127.0.0.1:{18091 + seat}/v1/models", "clients", "live window"))
                req = urllib.request.Request(f"http://127.0.0.1:{18091 + seat}/metrics", headers={"Authorization": f"Bearer {key}"})
                with urllib.request.urlopen(req, timeout=5) as r:
                    metrics = r.read().decode("utf-8", "replace")
                m = re.search(r'^vllm:cache_config_info\{([^}]*)\}', metrics, re.M)
                if m:
                    labels = dict(re.findall(r'(\w+)="([^"]*)"', m.group(1)))
                    for k in ("kv_cache_size_tokens", "kv_cache_max_concurrency", "block_size", "cache_dtype"):
                        if k in labels:
                            v = labels[k]
                            v = int(v) if v.isdigit() else (round(float(v), 2) if re.fullmatch(r"[0-9.]+", v) else v)
                            rows.append(row("seat-live", f"{unit} {k}", v, f"http://127.0.0.1:{18091 + seat}/metrics cache_config_info", "vLLM", "KV pool" if "kv" in k else "block / dtype"))
            except Exception as exc:  # noqa: BLE001 -- live is best-effort
                rows.append(row("seat-live", f"{unit} live read", f"unavailable: {type(exc).__name__}", "", "", ""))
    if live:
        try:
            req = urllib.request.Request("http://127.0.0.1:18099/health")
            with urllib.request.urlopen(req, timeout=5) as r:
                data = json.load(r)
            rows.append(row("seat-live", "omen-perception health", f"status={data.get('status')} ips={data.get('images_per_second')}", "http://127.0.0.1:18099/health", "door", "CPU perception lane health"))
        except Exception as exc:  # noqa: BLE001
            rows.append(row("seat-live", "omen-perception live read", f"unavailable: {type(exc).__name__}", "", "", ""))
    return rows


def collect_router() -> list[Row]:
    path = HOME / ".config" / "omen-vllm" / "haproxy.cfg"
    text = _read(path)
    rows = [row("router", "haproxy global maxconn", _grep(text, r"^\s*maxconn\s+(\d+)", cast=int), _line_of(path, r"^\s*maxconn"), "haproxy", "total open connections")]
    for t in ("connect", "client", "server", "queue"):
        v = _grep(text, rf"^\s*timeout {t}\s+(\d+)s", cast=int)
        rows.append(row("router", f"haproxy timeout {t}", v, _line_of(path, rf"timeout {t}") if v is not None else _rel(path), "haproxy",
                        {"connect": "backend connect", "client": "idle per request (client side)", "server": "idle per request (seat side)", "queue": "wait for a free server slot"}[t],
                        "" if v is not None else "not set"))
    for fe, port in re.findall(r"frontend (\w+)\n\s+bind 127\.0\.0\.1:(\d+)", text):
        rows.append(row("router", f"frontend {fe}", int(port), _line_of(path, f"frontend {fe}"), "HEARTH rung endpoint", "which lane a port is"))
    for be, body in re.findall(r"backend (\w+)\n((?:\s+.*\n)+)", text):
        servers = re.findall(r"server (\w+) 127\.0\.0\.1:(\d+)([^\n]*)", body)
        for name, port, rest in servers:
            mc = _grep(rest, r"maxconn (\d+)", cast=int)
            rows.append(row("router", f"backend {be} server {name}", f"127.0.0.1:{port}" + (f" maxconn {mc}" if mc else " (no maxconn)"), _line_of(path, f"server {name}"), "haproxy", "seat behind the lane; per-server maxconn queues overflow at the router", "" if mc else "no per-server maxconn: overflow queues inside vLLM"))
    return rows


def _toml(path: Path) -> dict:
    try:
        return tomllib.loads(_read(path))
    except (tomllib.TOMLDecodeError, OSError):
        return {}


def collect_backends() -> list[Row]:
    path = Path(os.environ.get("HEARTH_BACKENDS", str(PROD / "backends-linux.toml")))
    doc = _toml(path)
    rows = [row("rung", "default rung", doc.get("default"), _line_of(path, "^default"), "local_generate", "where untagged calls land")]
    for b in doc.get("backend", []):
        s = b.get("settings", {})
        name = b["name"]
        for k, bounds in (("context_tokens", "input + output tokens the seat holds"), ("context_bytes", "payload bytes admitted by the door (3.5 B/token, no output reserve)"),
                          ("max_tokens", "default output budget = the reserve local-work subtracts"), ("deliberate_max_tokens", "largest output a streamed inference.deliberate turn may ask for on this rung"), ("timeout_s", "HTTP timeout when the caller sets none (execution path always overrides)"),
                          ("parallel_slots", "HEARTH lease slots on this rung"),
                          ("flash_attention", "declared attention backend of the seat (true = FLASH_ATTN)"),
                          ("speculative", "declared MTP draft depth of the seat (mtp-k<N>)"),
                          ("images_per_second", "measured perception throughput on CPU"),
                          ("max_image_bytes", "largest image payload accepted")):
            if k in s:
                rows.append(row("rung", f"{name} {k}", s[k], _line_of(path, rf"^\s*{k}\s*=") , "backends pool", bounds))
        rows.append(row("rung", f"{name} endpoint", b.get("endpoint"), _line_of(path, f'name = "{name}"'), "door", "which router port"))
    text = _read(path)
    m = re.search(r"KV pool[^\n]*?(\d{2},\d{3}|\d{5})[^\n]*tokens", text)
    if m:
        rows.append(row("rung", "backends-linux.toml KV-pool comment", m.group(1).replace(",", ""), _line_of(path, r"KV pool"), "operator", "documentation of the dense seat's KV pool", "compared against the live kv_cache_size_tokens under --live"))
    return rows


def collect_routes_and_families() -> list[Row]:
    rows: list[Row] = []
    rp = Path(os.environ.get("HEARTH_LOCAL_WORK_ROUTES", str(PROD / "local-work-routes-linux.toml")))
    for lane, spec in _toml(rp).get("lane", {}).items():
        rows.append(row("local-work", f"lane {lane}", spec.get("backend"), _line_of(rp, rf"\[lane\.{lane}\]"), "submit_local_work", "which rung a lane is"))
    fp = Path(os.environ.get("HEARTH_ROUTING_FAMILIES", str(PROD / "routing-families-linux.toml")))
    fam = _toml(fp).get("family", {})
    for name, spec in sorted(fam.items()):
        if spec.get("refusal"):
            rows.append(row("family", f"family {name}", f"refusal: {spec['refusal']}", _line_of(fp, rf"\[family\.{name}\]"), "door refusal", "explicit refusal (missing capability)"))
            continue
        d = spec.get("depth_override") or {}
        val = f"{spec.get('model_id')}"
        if d.get("min_prompt_tokens"):
            val += f"; >= {d['min_prompt_tokens']} prompt tokens -> {d.get('model_id')}"
        if spec.get("min_prompt_tokens"):
            val += f"; >= {spec['min_prompt_tokens']} -> {spec.get('model_id')} else {spec.get('below_threshold_model_id')}"
        if spec.get("tags"):
            val += f"; tags {spec['tags']}"
        rows.append(row("family", f"family {name}", val, _line_of(fp, rf"\[family\.{name}\]"), "families.recommend (advisory) / local_generate tag route", "model + depth threshold (prompt tokens = payload bytes // 4)"))
    return rows


def collect_operations() -> list[Row]:
    path = Path(os.environ.get("HEARTH_OPERATIONS", str(REPO / "hearth" / "etc" / "operations.toml")))
    doc = _toml(path)
    rows = []
    for op, spec in doc.get("operation", {}).items():
        if op not in ("llm.chat", "inference.generate", "inference.deliberate", "work.produce"):
            continue
        if spec.get("streamed"):
            rows.append(row("operation", f"{op} streamed", True, _line_of(path, rf'\[operation\."{re.escape(op)}"\]'), "execution policy_for", "submit/watch only; the router's idle timers do not bound its deadline"))
        for k, bounds in (("max_tokens_ceiling", "largest output budget a job may ask for"), ("deadline_ceiling_s", "largest deadline; also the default when none is given"), ("max_prompt_bytes", "largest prompt")):
            rows.append(row("operation", f"{op} {k}", spec.get(k), _line_of(path, rf'\[operation\."{re.escape(op)}"\]'), "execution policy_for", bounds))
    return rows


def collect_door_code() -> list[Row]:
    rows = []
    inf = REPO / "hearth" / "toolsurface" / "inference.py"; t = _read(inf)
    rows.append(row("door", "local_generate default max_tokens (no rung value)", _grep(t, r"rmt = int\(setting\) if setting is not None else (\d+)", cast=int), _line_of(inf, r"else 1024"), "local_generate", "output when neither caller nor rung says"))
    rows.append(row("door", "local_generate DEFAULT_TIMEOUT_S", _grep(t, r"^DEFAULT_TIMEOUT_S = (\d+)", cast=int), _line_of(inf, "^DEFAULT_TIMEOUT_S"), "local_generate", "HTTP timeout when neither caller nor rung says", "never used on the execution path: it passes deadline - now"))
    rows.append(row("door", "files= per-file / total cap (bytes)", f"{_grep(t, r'^FILES_PER_FILE_CAP = (.+)$')} / {_grep(t, r'^FILES_TOTAL_CAP = (.+)$')}", _line_of(inf, "^FILES_PER_FILE_CAP"), "_pack_files", "packed file bytes", "unreachable on Linux: every rung's context_bytes is smaller"))
    rows.append(row("door", "family depth estimate", "payload_bytes // 4", _line_of(inf, r"// 4"), "families.recommend", "prompt_tokens for depth rules"))
    be = REPO / "hearth" / "toolsurface" / "backends.py"
    if "_output_reserve_rejection" in _read(be):
        rows.append(row("door", "payload admission rule (pin and tag route)", "payload_bytes <= context_bytes AND payload_bytes // 4 + max_tokens <= context_tokens", _line_of(be, r"def _output_reserve_rejection"), "select_backend", "admission", "reserve = caller max_tokens else the rung's"))
    else:
        rows.append(row("door", "payload admission rule (pin and tag route)", "payload_bytes <= context_bytes", _line_of(be, r"payload_bytes > pinned_context"), "select_backend", "admission", "reserves no output tokens"))
    lw = REPO / "hearth" / "localwork" / "service.py"; t = _read(lw)
    rows.append(row("local-work", "auto lane floor (evidence tokens -> deep)", _grep(t, r"floor = (\d+) if task_family == \"quote_retrieval\" else (\d+)", group=2, cast=int), _line_of(lw, r"floor = 4096"), "_lane", "fast vs deep", f"quote_retrieval floor {_grep(t, r'floor = (\d+) if', cast=int)}; evidence = source pack only, counted with the fast lane's tokenizer"))
    rows.append(row("local-work", "output_reserve fallback", _grep(t, r'settings.get\("max_tokens"\) or (\d+)', cast=int), _line_of(lw, r"output_reserve ="), "submit", "reserve when the rung declares none"))
    rows.append(row("local-work", "exact context check", "input_tokens + output_reserve <= context_tokens", _line_of(lw, r"input_tokens \+ output_reserve"), "submit", "refuses at submit"))
    rows.append(row("local-work", "tokenizer / git / apply timeouts (s)", f"{_grep(t, r'_server_token_count.*?timeout=(\d+)', cast=int) or 30} / 120 / 120", _line_of(lw, r"timeout=120"), "submit, validation", "submit latency; candidate validation"))
    tl = REPO / "hearth" / "toolsurface" / "local_work.py"; t = _read(tl)
    rows.append(row("local-work", "submit_local_work deadline_s default", _grep(t, r"deadline_s: int = (\d+)", cast=int), _line_of(tl, r"deadline_s: int ="), "MCP tool", "job deadline when the caller sets none"))
    ex = REPO / "hearth" / "execution" / "service.py"; t = _read(ex)
    rows.append(row("execution", "workers / max_pending", f"{_grep(t, r'workers: int = (\d+)', cast=int)} / {_grep(t, r'max_pending: int = (\d+)', cast=int)}", _line_of(ex, r"workers: int ="), "executor", "concurrent jobs / queue depth"))
    rows.append(row("execution", "parallel_slots clamp", "1..128", _line_of(ex, r"min\(value, 128\)"), "lease limit", "per-rung concurrency"))
    rows.append(row("execution", "provider HTTP timeout", "max(1, deadline - now)", _line_of(ex, r"int\(deadline - time.monotonic\(\)\)"), "_run_job", "the '1199'", "queue wait counts against the deadline"))
    on = REPO / "hearth" / "scheduler" / "ontology.py"; t = _read(on)
    rows.append(row("scheduler", "default inference duration (s)", _grep(t, r'"inference": ([0-9.]+)', cast=float), _line_of(on, r'"inference":'), "propose_schedule (advisory)", "job length estimate when capacity.json has no bucket"))
    return rows


def collect_sizer() -> list[Row]:
    """ADR-0050: the request sizer's declared numbers -- bins, gate, service port and timeout -- and
    which rungs carry the long-output tag it routes to."""
    rows: list[Row] = []
    try:
        from hearth.sizer import BINS, DEFAULT_SIZER_URL, DEFAULT_TIMEOUT_MS
    except Exception as exc:  # noqa: BLE001
        return [row("sizer", "hearth.sizer import", f"error: {type(exc).__name__}", "hearth/sizer", "door, execution service", "the sizer package must import")]
    hp = REPO / "hearth" / "sizer" / "heuristic.py"
    rows.append(row("sizer", "output bins (upper edge, tokens)", " ".join(f"{n}<{e}" for n, e in BINS[:-1]) + f" xl>={BINS[-2][1]}", _line_of(hp, "^BINS"), "size_heuristic -> admission reserve", "expected output tokens = the bin's edge", "ledger 2026-09-23..28: tokens_out p50 77 / p90 279 / p99 604 -> xs/s/m"))
    rows.append(row("sizer", "long bins (tool-long)", "l, xl", _line_of(hp, "^LONG_BINS"), "tool_execution -> tool_long_output refinement", "which bins move to the decode seat"))
    ops_env = HOME / ".config" / "hearth" / "hearth-ops.env"
    gate = _grep(_read(ops_env), r"^HEARTH_SIZER=(\S+)", default="unset (off)")
    rows.append(row("sizer", "HEARTH_SIZER gate (hearth-ops.env)", gate, _rel(ops_env), "size_request", "off | heuristic | npu", "off -> every route byte-identical to the unsized door"))
    cp = REPO / "hearth" / "sizer" / "client.py"
    rows.append(row("sizer", "encoder service url / client timeout (ms)", f"{DEFAULT_SIZER_URL} / {DEFAULT_TIMEOUT_MS}", _line_of(cp, "^DEFAULT_TIMEOUT_MS"), "size_request(mode=npu)", "on timeout the heuristic answers and the ledger says fallback_from"))
    path = Path(os.environ.get("HEARTH_BACKENDS", str(PROD / "backends-linux.toml")))
    long_rungs = [b["name"] for b in _toml(path).get("backend", []) if "tool-long" in (b.get("tags") or [])]
    rows.append(row("sizer", "rungs tagged tool-long", ", ".join(long_rungs) or "none", _rel(path), "family tool_long_output", "the decode seat(s)", "am4-tool-5070 decodes 110 tok/s vs the Ti's 85 (2026-09-28 02:43Z)"))
    return rows


def collect_lanes() -> list[Row]:
    rows = []
    bf = REPO / "fleet" / "bankedfire_linux.py"; t = _read(bf)
    rows.append(row("drain", "BANKEDFIRE_SLOTS default", _grep(t, r'"BANKEDFIRE_SLOTS", "([^"]+)"'), _line_of(bf, "BANKEDFIRE_SLOTS"), "bankedfire_linux.tick", "unattended in-flight work per lane", f"env now: {os.environ.get('BANKEDFIRE_SLOTS', '(unset)')}"))
    rows.append(row("drain", "brief deadline_s default", _grep(t, r'"deadline_s": int\(fields.get\("deadline_s", (\d+)\)\)', cast=int), _line_of(bf, r'fields.get\("deadline_s"'), "submit_args_from_brief", "local-work job deadline"))
    rows.append(row("drain", "proofing max_tokens / deadline_s", f"{_grep(t, r'\"task_family\": \"drafting\", \"max_tokens\": (\d+)', cast=int)} / {_grep(t, r'\"deadline_s\": (\d+), \"idempotency_key\"', cast=int)}", _line_of(bf, r'"task_family": "drafting"'), "proofing_args_from_brief", "proposal output / deadline"))
    rows.append(row("drain", "door MCP client timeout (s)", _grep(t, r"timeout=(\d+)\) as \(r, w, _\)", cast=int), _line_of(bf, r"streamablehttp_client"), "call_tool", "submit / status calls"))
    rows.append(row("drain", "systemd-run launch timeout (s)", _grep(t, r"subprocess.run\(argv, capture_output=True, text=True, timeout=(\d+)\)", cast=int), _line_of(bf, r"systemd-run"), "experiment / deepagents launch", ""))
    rows.append(row("drain", "skip backoff (days)", _grep(t, r"^SKIP_DAYS = (\d+)", cast=int), _line_of(bf, "^SKIP_DAYS"), "candidate_exclusions", "failed candidate retry"))
    timer = HOME / ".config" / "systemd" / "user" / "bankedfire-drain.timer"
    rows.append(row("drain", "tick interval", _grep(_read(timer), r"OnUnitActiveSec=(\S+)"), _rel(timer), "systemd", "how often the night loop looks"))
    pr = REPO / "fleet" / "presence_linux.py"
    rows.append(row("drain", "PRESENCE idle minutes", _grep(_read(pr), r"^DEFAULT_IDLE_MIN = (\d+)", cast=int), _line_of(pr, "^DEFAULT_IDLE_MIN"), "presence.report", "away threshold", f"env now: {os.environ.get('PRESENCE_IDLE_MIN', '(unset)')}"))
    ex = REPO / "fleet" / "experiment_linux.py"; t = _read(ex)
    rows.append(row("experiment", "RESTORE_MARGIN_MIN / DEFAULT_MAX_MINUTES / DEFAULT_RESTORE_BY", f"{_grep(t, r'^RESTORE_MARGIN_MIN = (\d+)')} / {_grep(t, r'^DEFAULT_MAX_MINUTES = (\d+)')} / {_grep(t, r'^DEFAULT_RESTORE_BY = \"([^\"]+)\"')}", _line_of(ex, "^RESTORE_MARGIN_MIN"), "Experiment.campaign_budget_s", "campaign wall clock"))
    rows.append(row("experiment", "seat wait (s)", _grep(t, r'str\(self.seat\), "(\d+)"', cast=int), _line_of(ex, r"WAIT_SCRIPT\), str\(self.seat\)"), "restart_and_wait", "seat restart"))
    da = REPO / "fleet" / "deepagents_linux.py"
    rows.append(row("deepagents-lane", "RUN_TIMEOUT_S (wrapper)", _grep(_read(da), r"^RUN_TIMEOUT_S = (\d+)", cast=int), _line_of(da, "^RUN_TIMEOUT_S"), "Delivery.run", "outer subprocess timeout"))
    ws = HOME / "bin" / "wait-vllm-seat.sh"
    rows.append(row("seat", "wait-vllm-seat default max (s)", _grep(_read(ws), r"max=\$\{2:-(\d+)\}", cast=int), _line_of(ws, r"max=\$\{2:-"), "operator, experiment lane", "seat startup wait"))
    mr = REPO / "tools" / "hearth-morning-report"
    rows.append(row("report", "morning report git/apply timeouts (s)", sorted({int(x) for x in re.findall(r"timeout=(\d+)\)", _read(mr))}), _line_of(mr, r"timeout=60"), "hearth-morning-report", "apply-check per candidate"))
    return rows


def collect_runner() -> list[Row]:
    rows = []
    root = Path(os.environ.get("DEEPAGENTS_LINUX", str(HOME / "work" / "deepagents-linux")))
    rl = root / "run_linux_delivery.py"; t = _read(rl)
    for name, ctx in re.findall(r'"(\w[\w-]*)": \{"model": "[^"]+", "endpoint": "[^"]+",\s*"token_env": "\w+", "context": (\d+)', t):
        rows.append(row("runner", f"ROUTES.{name}.context", int(ctx), _line_of(rl, f'"{name}": \\{{"model"'), "AccountedTransport context check, summarization trigger", "prompt + output + 32 <= context"))
    rows.append(row("runner", "output_limit report / code", f"{_grep(t, r'output_limit = (\d+) if args.report else (\d+)', group=1)} / {_grep(t, r'output_limit = (\d+) if args.report else (\d+)', group=2)}", _line_of(rl, r"output_limit = "), "PinnedChat max_tokens", "output tokens per model call"))
    attempts = _grep(t, r"RequestBudget\(deadline=time.time\(\) \+ \d+, limit=(\d+)\)", cast=int) or _grep(t, r"attempt_limit = (max\(.*\))")
    rows.append(row("runner", "RequestBudget limit (attempts)", attempts, _line_of(rl, r"attempt_limit = |RequestBudget\("), "AccountedTransport.dispatch", "physical inference calls per run", "scaled by source lines since 2026-09-28" if isinstance(attempts, str) else ""))
    deadline = _grep(t, r"RequestBudget\(deadline=time.time\(\) \+ (\d+)", cast=int) or _grep(t, r"^DEADLINE_S = (\d+)", cast=int)
    rows.append(row("runner", "RequestBudget deadline (s)", deadline, _line_of(rl, r"^DEADLINE_S = |RequestBudget\("), "AccountedTransport", "run wall clock"))
    evict = _grep(t, r"tool_token_limit_before_evict=(\d+)", cast=int)
    evict_expr = _grep(t, r"evict_tokens = (max\(.*\))")
    dctx = _grep(t, r'"omen-dense": \{"model": "[^"]+", "endpoint": "[^"]+",\s*"token_env": "\w+", "context": (\d+)', cast=int)
    if evict is None and evict_expr and dctx:
        evict = max(2048, dctx // 8)   # the formula evaluated for the dense route
    rows.append(row("runner", "tool_token_limit_before_evict", evict, _line_of(rl, r"evict_tokens = |tool_token_limit_before_evict"), "EvictingFilesystem", "tool result size before it is moved to /large_tool_results (4 chars/token)", f"= {evict_expr} on the dense route" if evict_expr else ""))
    recursion = _grep(t, r'"recursion_limit": (\d+)', cast=int) or _grep(t, r"^RECURSION_LIMIT = (\d+)", cast=int)
    rows.append(row("runner", "recursion_limit", recursion, _line_of(rl, r"^RECURSION_LIMIT = |recursion_limit"), "LangGraph invoke", "graph supersteps (~2 per model turn)"))
    rows.append(row("runner", "httpx / PinnedChat timeout (s)", _grep(t, r"timeout=(\d+), trust_env", cast=int), _line_of(rl, r"httpx.Client"), "per request", ""))
    rows.append(row("runner", "default --backend", _grep(t, r'choices=tuple\(ROUTES\), default="([^"]+)"'), _line_of(rl, r'default="omen"'), "CLI", "route when the wrapper passes none"))
    at = root / "poc" / "accounted_transport.py"; t = _read(at)
    rows.append(row("runner", "RequestBudget default limit", _grep(t, r"def __init__\(self, \*, deadline, limit=(\d+)\)", cast=int), _line_of(at, r"limit=32"), "any caller that omits limit", "attempts"))
    fields = re.findall(r'payload\.get\("(\w+)"', t.split("def handle_request", 1)[1].split("logical_id", 1)[0]) if "def handle_request" in t else []
    bound = _grep(t, r"0 < output <= (\w+)")
    if bound and not bound.isdigit():
        bound = f"{bound}={_grep(t, rf'^{bound} = (\d+)', cast=int)}"
    rows.append(row("runner", "transport output guard", f"reads {'|'.join(fields)}; requires 0 < output <= {bound}", _line_of(at, r"0 < output <="), "handle_request", "output cap per call", "" if "max_completion_tokens" in fields else "langchain sends max_completion_tokens, so the guard sees the default"))
    return rows


AM4_SSH = "10.44.0.2"
AM4_PROFILE_ALIASES = {"dense-tp2": ["am4-dense-27b"], "tool-pair": ["am4-tool-4070ti", "am4-tool-5070"]}


def _ssh_am4(cmd: str, timeout: int = 8) -> Optional[str]:
    try:
        out = subprocess.run(["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=4", AM4_SSH, cmd],
                             capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.TimeoutExpired):
        return None
    return out.stdout if out.returncode == 0 else None


def collect_am4(live: bool) -> list[Row]:
    """AM4 serves one PROFILE at a time; the profile file and the per-seat env files are the declared
    facts, the facade's /oxen/ready is the live one. Read over the direct cable (ADR-0014)."""
    rows: list[Row] = []
    cfg = REPO / "am4-fleet-node" / "config"
    for seat in ("4070ti", "5070"):
        env: dict[str, str] = {}
        for line in _read(cfg / f"seat-{seat}.env").splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("="); env[k.strip()] = v.strip()
        src = f"repo/am4-fleet-node/config/seat-{seat}.env"
        rows.append(row("am4-seat", f"am4-tool@{seat} served model", env.get("AM4_SERVED_NAME"), src, "facade alias", "which alias answers"))
        rows.append(row("am4-seat", f"am4-tool@{seat} max_model_len", int(env.get("AM4_MAX_MODEL_LEN") or 0) or None, src, "vLLM", "input + output tokens per request"))
        rows.append(row("am4-seat", f"am4-tool@{seat} max_num_seqs", int(env.get("AM4_MAX_NUM_SEQS") or 0) or None, src, "vLLM scheduler", "concurrent sequences"))
        rows.append(row("am4-seat", f"am4-tool@{seat} gpu_memory_utilization", float(env.get("AM4_GPU_MEM_UTIL") or 0) or None, src, "vLLM", "VRAM fraction on one card"))
        rows.append(row("am4-seat", f"am4-tool@{seat} tool / reasoning parser", f"{env.get('AM4_TOOL_PARSER')} / {env.get('AM4_REASONING_PARSER')}", src, "vLLM", "native tool-call parsing"))
        rows.append(row("am4-seat", f"am4-tool@{seat} card", env.get("AM4_GPU_UUID"), src, "CUDA_VISIBLE_DEVICES", "the one card this seat may use (UUID, ADR-0042)"))
    canary = _read(REPO / "am4-fleet-node" / "scripts" / "run-vllm-canary.sh")
    rows.append(row("am4-seat", "am4-vllm (dense-tp2) max_model_len", _grep(canary, r"--max-model-len (\d+)", cast=int), "repo/am4-fleet-node/scripts/run-vllm-canary.sh", "vLLM TP2", "window of the dense profile"))
    rows.append(row("am4-seat", "am4-vllm (dense-tp2) max_num_seqs", _grep(canary, r"--max-num-seqs (\d+)", cast=int), "repo/am4-fleet-node/scripts/run-vllm-canary.sh", "vLLM TP2", "concurrent sequences"))
    if live:
        prof = (_ssh_am4("cat ~/.config/am4-fleet/profile") or "").strip() or "unreadable"
        rows.append(row("am4-live", "am4 profile", prof, "am4:~/.config/am4-fleet/profile", "readiness probe, occupancy probes, DeepAgents wrapper", "which alias set is live"))
        token = None
        for line in _read(HOME / ".config" / "omen-vllm" / "hearth-backends.env").splitlines():
            if line.startswith("AM4_VLLM_TOKEN="):
                token = line.split("=", 1)[1].strip().strip('"')
        if token:
            for alias in ("am4-dense-27b", "am4-tool-4070ti", "am4-tool-5070"):
                try:
                    req = urllib.request.Request(f"http://{AM4_SSH}:8090/oxen/ready?alias={alias}", headers={"Authorization": f"Bearer {token}"})
                    with urllib.request.urlopen(req, timeout=5) as r:
                        d = json.load(r)
                    rdy = next((a.get("ready") for a in d.get("aliases", []) if a.get("alias") == alias), None)
                    rows.append(row("am4-live", f"facade alias {alias} ready", rdy, f"http://{AM4_SSH}:8090/oxen/ready?alias={alias}", "HEARTH rung occupancy", "live readiness of the alias"))
                except Exception as exc:  # noqa: BLE001
                    rows.append(row("am4-live", f"facade alias {alias} ready", f"unavailable: {type(exc).__name__}", "", "", ""))
    return rows


def collect_gateway() -> list[Row]:
    unit = HOME / ".config" / "systemd" / "user" / "hearth-production.service"
    t = _read(unit); exec_line = next((l for l in t.splitlines() if l.startswith("ExecStart=")), "")
    return [row("door", "gateway tool dispatch", "threaded (asyncio.to_thread per call)" if "--threaded-tools" in exec_line else "on the event loop (one call at a time)",
                _rel(unit), "FastMCP", "how many door calls run at once",
                "measured 2026-09-28: 8 parallel 5 s calls took 45 s serialized, 12 s threaded")]


def collect_clients() -> list[Row]:
    rows = []
    cx = HOME / ".codex" / "config.toml"; t = _read(cx)
    rows.append(row("client", "codex mcp tool_timeout_sec", _grep(t, r"^tool_timeout_sec = (\d+)", cast=int), _line_of(cx, "^tool_timeout_sec"), "Codex", "longest door call"))
    try:
        cj = json.loads(_read(HOME / ".claude.json"))
        rows.append(row("client", "claude code hearth timeout (ms)", cj["mcpServers"]["hearth"].get("timeout"), "~/.claude.json mcpServers.hearth.timeout", "Claude Code", "longest door call"))
    except Exception:  # noqa: BLE001
        pass
    return rows


def collect_measured() -> list[Row]:
    """p90 of the dense lane's work.produce runs from the execution ledger (aggregates only)."""
    path = PROD / "var" / "execution" / "events.ndjson"
    outs, durs = [], []
    try:
        with path.open("rb") as fh:
            for raw in fh:
                if b'"invocation.succeeded"' not in raw or b'"work.produce"' not in raw and b'omen-dense-27b' not in raw:
                    continue
                try:
                    e = json.loads(raw)
                except ValueError:
                    continue
                if e.get("event_type") != "invocation.succeeded":
                    continue
                o = e.get("observed") or {}
                if o.get("backend") != "omen-dense-27b":
                    continue
                if o.get("tokens_out") and o.get("duration_ms"):
                    outs.append(int(o["tokens_out"])); durs.append(int(o["duration_ms"]))
    except OSError:
        return []
    if not outs:
        return []
    rate = [1000.0 * o / d for o, d in zip(outs, durs) if d]
    rate.sort(); outs.sort(); durs.sort()
    p90 = lambda xs: xs[min(len(xs) - 1, int(0.9 * (len(xs) - 1)))]  # noqa: E731
    return [row("measured", "omen-dense-27b invocations (n)", len(outs), _rel(path), "sizing rules", "sample"),
            row("measured", "omen-dense-27b tokens_out p90 / max", f"{p90(outs)} / {outs[-1]}", _rel(path), "", "how close outputs come to the cap"),
            row("measured", "omen-dense-27b duration_ms p90 / max", f"{p90(durs)} / {durs[-1]}", _rel(path), "", "how close jobs come to the deadline"),
            row("measured", "omen-dense-27b decode tok/s median", round(rate[len(rate) // 2], 1), _rel(path), "deadline derivation", "output / duration (prefill included, so a floor)")]


def _detect_omen_profile() -> str:
    pfile = HOME / ".config" / "omen-vllm" / "profile"
    if pfile.is_file():
        text = _read(pfile).strip()
        if text:
            return text
    return "two-lane"


def collect_configurations(live: bool) -> list[Row]:
    """ADR-0052: whole-lab serving configurations (day, memsplice, experiments)."""
    rows: list[Row] = []
    cfg_path = Path(os.environ.get("HEARTH_LAB_CONFIGURATIONS", str(REPO / "host" / "lab-configurations.toml")))
    if not cfg_path.is_file():
        alt = HOME / ".config" / "omen-vllm" / "lab-configurations.toml"
        if alt.is_file():
            cfg_path = alt
    doc = _toml(cfg_path)
    configs = doc.get("configuration", {})
    for cname, cspec in sorted(configs.items()):
        tuple_val = f"{cspec.get('omen_profile')} / {cspec.get('am4_profile')} / {cspec.get('fx99_state')}"
        rows.append(row("configuration", f"config {cname} omen/am4/fx99", tuple_val,
                        _rel(cfg_path), "lab-config", "declared whole-lab profile tuple", cspec.get("description", "")))
        for bname, bspec in sorted(cspec.get("backends", {}).items()):
            st = bspec.get("status", "unknown")
            val = f"status={st}"
            if st == "live":
                val += f" ctx={bspec.get('context_tokens')} slots={bspec.get('parallel_slots')} max_tokens={bspec.get('max_tokens')}"
            rows.append(row("configuration", f"config {cname} backend {bname}", val,
                            _rel(cfg_path), "routing invariants", "expected backend status under configuration"))

    omen_prof = _detect_omen_profile()
    if live:
        am4_prof = (_ssh_am4("cat ~/.config/am4-fleet/profile") or "").strip() or "unreadable"
        active_name = None
        for cname, cspec in configs.items():
            if cspec.get("omen_profile") == omen_prof and cspec.get("am4_profile") == am4_prof:
                active_name = cname
                break
        rows.append(row("configuration", "active configuration", active_name or "unknown",
                        "omen-profile + am4-profile", "sizing_map invariants", f"omen={omen_prof}, am4={am4_prof}"))
        rows.append(row("configuration", "active omen profile", omen_prof,
                        "~/.config/omen-vllm/profile", "lab-config", "active OMEN seat profile"))
        rows.append(row("configuration", "active am4 profile", am4_prof,
                        "am4:~/.config/am4-fleet/profile", "lab-config", "active AM4 seat profile"))
    else:
        rows.append(row("configuration", "active configuration", "unprobed (requires --live)",
                        "", "", "pass --live to detect whole-lab configuration"))
        rows.append(row("configuration", "active omen profile", omen_prof,
                        "~/.config/omen-vllm/profile", "lab-config", "active OMEN seat profile"))
    return rows


def collect(live: bool, measured: bool) -> list[Row]:
    rows: list[Row] = []
    for fn in (collect_seats, collect_router, collect_backends, collect_routes_and_families, collect_operations,
               collect_door_code, collect_gateway, collect_lanes, collect_runner, collect_clients, collect_am4,
               collect_sizer, collect_configurations):
        rows.extend(fn(live) if fn in (collect_seats, collect_am4, collect_configurations) else fn())
    if measured:
        rows.extend(collect_measured())
    return sorted(rows, key=lambda r: (r["layer"], r["setting"]))


# --- invariants -------------------------------------------------------------------------------

def _val(rows: list[Row], setting: str, default=None):
    for r in rows:
        if r["setting"] == setting:
            return r["value"]
    return default


def _num(v, default=None):
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def invariants(rows: list[Row]) -> list[dict]:
    """Each rule cites the observation that earned it. Returns the violations."""
    out: list[dict] = []
    def fail(rule: str, detail: str, earned_by: str):
        out.append({"rule": rule, "detail": detail, "earned_by": earned_by})
    rungs = {}
    for r in rows:
        if r["layer"] == "rung" and " " in r["setting"]:
            name, key = r["setting"].split(" ", 1); rungs.setdefault(name, {})[key] = r["value"]
    seat_for = {"omen-vllm": "omen-vllm@1", "omen-dense-27b": "omen-vllm@0",
                "omen-dense-27b-b": "omen-vllm@1"}
    # Declarations for mutually exclusive profiles coexist in the pool. Only compare
    # a backend with its occupied seat, while keeping absent-route checks below.
    active_cfg = _val(rows, "active configuration")
    for rung, seat in list(seat_for.items()):
        status = str(_val(rows, f"config {active_cfg} backend {rung}", ""))
        served = str(_val(rows, f"{seat} served model", ""))
        if "status=absent" in status:
            del seat_for[rung]
        elif "status=live" not in status and served:
            expected = "qwen3-30b-a3b" if rung == "omen-vllm" else "qwen3.8-27b"
            if expected not in served:
                del seat_for[rung]
    # 1. rung context == seat window
    for rung, seat in seat_for.items():
        s = rungs.get(rung, {}); mml = _val(rows, f"{seat} max_model_len")
        if s.get("context_tokens") is not None and mml is not None and int(s["context_tokens"]) != int(mml):
            fail("rung-context-equals-seat-window", f"{rung} context_tokens {s['context_tokens']} != {seat} max_model_len {mml}", "the 30B seat refused 65536 at startup (07-serving-recipe.md); the declaration must be the seat's")
    # 2. max_num_seqs >= parallel_slots and slots x typical <= KV
    for rung, seat in seat_for.items():
        s = rungs.get(rung, {}); seqs = _num(_val(rows, f"{seat} max_num_seqs")); slots = _num(s.get("parallel_slots"))
        if seqs is not None and slots is not None and seqs < slots:
            fail("seat-admits-at-least-the-leases", f"{seat} max_num_seqs {seqs:g} < {rung} parallel_slots {slots:g}", "leases would queue on a seat that cannot admit them")
        kv = _num(_val(rows, f"{seat} kv_cache_size_tokens"))
        if kv is not None and slots is not None and s.get("context_tokens") is not None and s.get("max_tokens") is not None:
            # A realistic concurrent request: measured p90 input on the dense lane was 19.5K of a
            # 65,536 window (0.30) and p90 output 5.7K of a 16,384 reserve; half the reserve is the
            # conservative allowance. vLLM preempts when the pool is exhausted, so the sum must fit.
            typical = 0.30 * float(s["context_tokens"]) + 0.5 * float(s["max_tokens"])
            if slots * typical > kv:
                fail("slots-fit-the-kv-pool", f"{rung}: {slots:g} slots x typical {typical:.0f} tokens = {slots * typical:.0f} > {seat} KV pool {kv:.0f}", "a work.produce waited 9.3 s for a slot on 2026-09-27 at 3 slots; preemption follows oversubscription")
    # 2b. a rung's declared recipe is the seat's (the serving profile in a capability record is the declaration)
    for rung, seat in seat_for.items():
        s = rungs.get(rung, {}); attn = _val(rows, f"{seat} attention_backend"); k = _val(rows, f"{seat} mtp_k")
        if s and attn is not None and bool(s.get("flash_attention")) != (attn == "FLASH_ATTN"):
            fail("declared-recipe-is-the-seat", f"{rung} flash_attention {s.get('flash_attention')} but {seat} attention_backend {attn}", "the 27B ran 4 to 20 times faster on Flash (2026-10-03); a record that hides the backend mixes two configurations")
        if s.get("speculative") is not None and str(s["speculative"]) != f"mtp-k{k}":
            fail("declared-recipe-is-the-seat", f"{rung} speculative {s['speculative']} but {seat} mtp_k {k}", "the declared draft depth must be the seat's")
    # 3. operation ceilings vs rungs
    ceil = {}
    for r in rows:
        if r["layer"] == "operation" and r["setting"].endswith(" max_tokens_ceiling"):
            ceil[r["setting"].split(" ")[0]] = _num(r["value"])
    max_reserve = max((_num(s.get("max_tokens"), 0) for s in rungs.values()), default=0)
    max_deliberate = max((_num(s.get("deliberate_max_tokens"), 0) for s in rungs.values()), default=0)
    for op, c in ceil.items():
        reserve = max_deliberate if op == "inference.deliberate" else max_reserve
        if c and c > reserve and (reserve or op == "inference.deliberate"):
            fail("operation-ceiling-within-the-largest-rung-reserve", f"{op} max_tokens_ceiling {c:g} > largest rung {'deliberate_max_tokens' if op == 'inference.deliberate' else 'max_tokens'} {reserve:g}", "a rung's max_tokens is what its seat is declared to serve as output; an operation that allows more admits a request no seat can complete (a 32,768 output on the 40,960 seat leaves 8K for input)")
    wp = ceil.get("work.produce")
    dense = rungs.get("omen-dense-27b", {})
    if wp and dense.get("max_tokens") is not None and _num(dense["max_tokens"]) > wp:
        fail("rung-reserve-within-ceiling", f"omen-dense-27b max_tokens {dense['max_tokens']} > work.produce ceiling {wp:g}", "a submit at the rung's own default would be refused at the ceiling")
    # 4. admission reserves output
    if _val(rows, "payload admission rule (pin and tag route)") == "payload_bytes <= context_bytes":
        fail("door-admission-reserves-output", "local_generate admits payload <= context_bytes and reserves nothing for max_tokens", "the pinned-rung refusal exists to fail at the door, not the server; today a full payload plus the default output overflows omen-vllm (40,960 + 8,192), am4 (16,384 + 8,192) and fx99 (4,096 + 2,048)")
    # 5. deadlines and timeouts chain
    dl = _num(_val(rows, "work.produce deadline_ceiling_s")); rate = _num(_val(rows, "omen-dense-27b decode tok/s median"))
    if dl and wp and rate:
        need = wp / rate + 60
        if need > dl:
            fail("deadline-covers-the-output", f"work.produce ceiling {wp:g} tokens at {rate:g} tok/s needs ~{need:.0f} s > deadline_ceiling_s {dl:g}", "the 5,690-token candidate took 545 s on 2026-09-27; a full 8,192 needs ~790 s + prefill")
    sub_dl = _num(_val(rows, "submit_local_work deadline_s default"))
    if sub_dl and dl and sub_dl < dl:
        pass  # a lower default than the ceiling is allowed; recorded in the table
    # Every operation's deadline, not only work.produce's. A streamed operation is submit/watch and its router
    # timers are idle timers (each chunk resets them), so it is bounded by none of these client timeouts.
    for op in sorted(r["setting"].rsplit(" ", 1)[0] for r in rows if r["layer"] == "operation" and r["setting"].endswith(" deadline_ceiling_s")):
        op_dl = _num(_val(rows, f"{op} deadline_ceiling_s"))
        if _val(rows, f"{op} streamed") or not op_dl:
            continue
        for who, key, scale in (("haproxy timeout server", "haproxy timeout server", 1), ("codex mcp tool_timeout_sec", "codex mcp tool_timeout_sec", 1), ("claude code hearth timeout (ms)", "claude code hearth timeout (ms)", 1000)):
            v = _num(_val(rows, key))
            if v is not None and v / scale < op_dl:
                fail("client-timeouts-cover-the-deadline", f"{op}: {who} {v:g}{'ms' if scale == 1000 else 's'} < deadline_ceiling_s {op_dl:g}", "a door call that outlives its client timeout is reported as a client error, not a result")
    if str(_val(rows, "gateway tool dispatch", "")).startswith("on the event loop"):
        fail("door-serves-calls-concurrently", "hearth-production.service runs the gateway without --threaded-tools", "2026-09-28 00:54Z: eight parallel local_generate pins to the 8-slot MoE lane completed 5 s apart; the seat never saw more than one request")
    if _val(rows, "haproxy timeout queue") is None:
        fail("router-queues-overflow", "haproxy has no per-server maxconn and no timeout queue", "with max_num_seqs 16 on both seats, the 17th request waits inside vLLM with no router-side bound")
    # 6. runner budgets vs route
    for name, rung in (("omen", "omen-vllm"), ("omen-dense", "omen-dense-27b")):
        rc = _num(_val(rows, f"ROUTES.{name}.context")); sc = _num(rungs.get(rung, {}).get("context_tokens"))
        if rc is not None and sc is not None and rc != sc:
            fail("runner-context-equals-seat", f"ROUTES.{name}.context {rc:g} != {rung} context_tokens {sc:g}", "the runner's own context check and summarization trigger use this number")
    rd = _num(_val(rows, "RequestBudget deadline (s)")); wt = _num(_val(rows, "RUN_TIMEOUT_S (wrapper)"))
    if rd and wt and wt < rd + 60:
        fail("wrapper-outlives-the-runner", f"RUN_TIMEOUT_S {wt:g} < runner deadline {rd:g} + 60", "a wrapper that kills first leaves no result.json")
    ev = _num(_val(rows, "tool_token_limit_before_evict")); dctx = _num(_val(rows, "ROUTES.omen-dense.context"))
    if ev is not None and dctx and ev < dctx / 16:
        fail("eviction-scales-with-context", f"tool_token_limit_before_evict {ev:g} < ROUTES.omen-dense.context / 16 ({dctx / 16:.0f})", "2026-09-27 retry: a 1,500-token preview cap on a 65K lane produced 12 read-only calls and 5 evicted files, and the attempt budget ran out")
    guard = str(_val(rows, "transport output guard", ""))
    if "max_completion_tokens" not in guard:
        fail("guard-reads-the-field-langchain-sends", f"transport output guard {guard}", "measured 2026-09-27: every request carried max_completion_tokens=3072 and the guard checked a default 2048")
    # 6b. AM4 profile rungs
    for rung, seat in (("am4-tool-4070ti", "am4-tool@4070ti"), ("am4-tool-5070", "am4-tool@5070")):
        s_ = rungs.get(rung, {}); mml = _val(rows, f"{seat} max_model_len")
        if s_.get("context_tokens") is not None and mml is not None and int(s_["context_tokens"]) != int(mml):
            fail("am4-rung-context-equals-seat-window", f"{rung} context_tokens {s_['context_tokens']} != {seat} max_model_len {mml}", "the AM4 tool seats declare their window in seat-*.env; the rung must repeat it exactly")
        rc = _num(_val(rows, f"ROUTES.{rung}.context")); 
        if rc is not None and mml is not None and rc != float(mml):
            fail("runner-context-equals-seat", f"ROUTES.{rung}.context {rc:g} != {seat} max_model_len {mml}", "the runner's own context check uses this number")
    prof = _val(rows, "am4 profile")
    if prof in ("dense-tp2", "tool-pair"):
        expected = {"dense-tp2": ["am4-dense-27b"], "tool-pair": ["am4-tool-4070ti", "am4-tool-5070"]}[prof]
        for alias in ("am4-dense-27b", "am4-tool-4070ti", "am4-tool-5070"):
            rdy = _val(rows, f"facade alias {alias} ready")
            if rdy is None or isinstance(rdy, str):
                continue
            if (alias in expected) != bool(rdy):
                fail("am4-profile-aliases-served", f"profile {prof}: alias {alias} ready={rdy}", "one profile is live at a time; an alias ready outside its profile means the switch left a seat running (or the profile file lies)")
    # 6c. the request sizer (ADR-0050)
    gate = str(_val(rows, "HEARTH_SIZER gate (hearth-ops.env)", "unset (off)"))
    if gate not in ("off", "heuristic", "npu", "unset (off)"):
        fail("sizer-gate-is-a-known-mode", f"HEARTH_SIZER={gate}", "an unknown value reads as off silently; the operator meant something else")
    long_rungs = {x.strip() for x in str(_val(rows, "rungs tagged tool-long", "")).split(",") if x.strip() and x.strip() != "none"}
    if long_rungs and long_rungs != {"am4-tool-5070"}:
        fail("tool-long-only-on-the-decode-seat", f"rungs tagged tool-long: {sorted(long_rungs)}", "the tag exists to put l/xl output on the faster decoder; a second carrier makes the split a coin toss")
    bins = str(_val(rows, "output bins (upper edge, tokens)", ""))
    xl_edge = _num(bins.rsplit(">=", 1)[-1]) if ">=" in bins else None
    for rung in long_rungs:
        mt = _num(rungs.get(rung, {}).get("max_tokens"))
        if xl_edge and mt is not None and mt < xl_edge:
            fail("long-rung-budget-covers-the-xl-bin", f"{rung} max_tokens {mt:g} < xl bin edge {xl_edge:g}", "the sizer sends xl output here; a rung budget below the edge truncates what the sizer promised room for")
    # 6d. perception lane invariants (task 13)
    perc = rungs.get("omen-perception")
    if perc:
        ips = _num(perc.get("images_per_second"))
        mib = _num(perc.get("max_image_bytes"))
        if ips is None or ips <= 0:
            fail("perception-declares-throughput", "omen-perception missing images_per_second or <= 0", "perception lane declares images_per_second instead of context_tokens")
        if mib is None or mib <= 0:
            fail("perception-declares-max-image-bytes", "omen-perception missing max_image_bytes or <= 0", "perception lane declares max_image_bytes instead of context_bytes")
    # 7. stale comments
    for r in rows:
        if r["setting"].endswith("says 'staged'") and r["value"] is True:
            fail("active-drop-in-says-staged", r["source"], "an operator reading the drop-in dir cannot tell what is live")
        if " set by " in r["setting"] and "drop-ins" in r["setting"]:
            fail("one-drop-in-per-key", f"{r['setting']}: {r['value']}", "seat 0's max-model-len.conf (40960) is overridden by stage2-27b-mtp.conf (65536); its comment describes the other checkpoint")
    kv_comment = _num(_val(rows, "backends-linux.toml KV-pool comment")); kv_live = _num(_val(rows, "omen-vllm@0 kv_cache_size_tokens"))
    if kv_comment and kv_live and abs(kv_comment - kv_live) > 0.25 * kv_live:
        fail("kv-comment-matches-live", f"backends-linux.toml says KV pool {kv_comment:.0f}; live seat 0 reports {kv_live:.0f}", "the pool varies per start (76,706 and 99,048 seen on the same config, 2026-09-27); the comment must say so and stay within 25%")
    # 8. Whole-lab configuration invariants (ADR-0052, task 8)
    active_cfg = _val(rows, "active configuration")
    if active_cfg is not None and not str(active_cfg).startswith("unprobed"):
        omen_p = _val(rows, "active omen profile")
        am4_p = _val(rows, "active am4 profile")
        if active_cfg == "unknown" or not active_cfg:
            fail("active-configuration-detected",
                 f"no lab configuration matches active profiles (omen={omen_p}, am4={am4_p})",
                 "every operating state of the lab must be a named configuration in host/lab-configurations.toml (ADR-0052, task 8)")
        else:
            expected_live: set[str] = set()
            expected_absent: set[str] = set()
            cfg_prefix = f"config {active_cfg} backend "
            for r in rows:
                if r["layer"] == "configuration" and r["setting"].startswith(cfg_prefix):
                    bname = r["setting"][len(cfg_prefix):]
                    val_str = str(r["value"])
                    if "status=live" in val_str:
                        expected_live.add(bname)
                    elif "status=absent" in val_str:
                        expected_absent.add(bname)

            # Expected live backends must be serving
            for b in sorted(expected_live):
                if b == "omen-vllm":
                    s1_live = _val(rows, "omen-vllm@1 live read")
                    s1_models = _val(rows, "omen-vllm@1 /v1/models")
                    if s1_live and "unavailable" in str(s1_live):
                        fail("expected-live-backends-serving", f"omen-vllm expected live under {active_cfg} but seat 1 is unavailable: {s1_live}", "live backends must be UP and responding to /v1/models")
                    elif s1_models is None and s1_live is not None:
                        fail("expected-live-backends-serving", f"omen-vllm expected live under {active_cfg} but seat 1 is not serving", "live backends must be UP and responding to /v1/models")
                elif b in ("omen-dense-27b", "omen-dense-27b-b"):
                    seat = 0 if b == "omen-dense-27b" else 1
                    live_read = _val(rows, f"omen-vllm@{seat} live read")
                    models = _val(rows, f"omen-vllm@{seat} /v1/models")
                    if live_read and "unavailable" in str(live_read):
                        fail("expected-live-backends-serving", f"{b} expected live under {active_cfg} but seat {seat} is unavailable: {live_read}", "live backends must be UP and responding to /v1/models")
                    elif (models is not None and "qwen3.8-27b" not in str(models)) or (models is None and live_read is not None):
                        fail("expected-live-backends-serving", f"{b} expected live under {active_cfg} but seat {seat} is serving {models}", "live backends must serve their declared model")
                elif b in ("am4-vllm", "am4-tool-4070ti", "am4-tool-5070"):
                    alias = "am4-dense-27b" if b == "am4-vllm" else b
                    rdy = _val(rows, f"facade alias {alias} ready")
                    if rdy is not None and rdy is not True:
                        fail("expected-live-backends-serving", f"{b} expected live under {active_cfg} but facade alias {alias} ready={rdy}", "live backends must report ready=True on their facade alias")
                elif b == "omen-perception":
                    p_live = _val(rows, "omen-perception live read")
                    if p_live and "unavailable" in str(p_live):
                        fail("expected-live-backends-serving", f"omen-perception expected live under {active_cfg} but perception service is unavailable: {p_live}", "live backends must be UP and responding to /health")

            # Expected absent backends must not be routable
            for b in sorted(expected_absent):
                if _val(rows, "default rung") == b:
                    fail("expected-absent-backends-not-routable", f"backend {b} expected absent under {active_cfg} but is default rung", "untagged requests fall through to the default rung")
                for r in rows:
                    if r["layer"] == "local-work" and r["setting"].startswith("lane ") and r["value"] == b:
                        lane_name = r["setting"]
                        fail("expected-absent-backends-not-routable", f"backend {b} expected absent under {active_cfg} but pinned by {lane_name}", "local-work lanes must not pin absent backends")
                if b in ("am4-vllm", "am4-tool-4070ti", "am4-tool-5070"):
                    alias = "am4-dense-27b" if b == "am4-vllm" else b
                    rdy = _val(rows, f"facade alias {alias} ready")
                    if rdy is True:
                        fail("expected-absent-backends-not-routable", f"backend {b} expected absent under {active_cfg} but facade alias {alias} ready=True", "an absent backend must not be ready in the facade")
                if b == "omen-dense-27b":
                    if any(r["layer"] == "rung" and r["setting"].startswith("omen-dense-27b ") for r in rows):
                        fail("expected-absent-backends-not-routable", f"backend {b} expected absent under {active_cfg} but declared in backends pool with tags and no occupancy probe", "an absent backend on OMEN without an occupancy probe accepts tag traffic")

            # Routing families must not resolve to absent backends
            for r in rows:
                if r["layer"] != "family":
                    continue
                fam_name = r["setting"].split("family ", 1)[1]
                fam_val = str(r["value"])
                if "refusal:" in fam_val or fam_name in ("document_ocr", "chart_diagram", "screenshot_grounded"):
                    continue

                resolved_backend: Optional[str] = None
                if fam_name in ("code_fix", "code_review", "long_review", "quote_retrieval"):
                    resolved_backend = "omen-dense-27b"
                elif fam_name in ("tool_execution",):
                    ti_ready = _val(rows, "facade alias am4-tool-4070ti ready") is True and "am4-tool-4070ti" not in expected_absent
                    s5_ready = _val(rows, "facade alias am4-tool-5070 ready") is True and "am4-tool-5070" not in expected_absent
                    if ti_ready:
                        resolved_backend = "am4-tool-4070ti"
                    elif s5_ready:
                        resolved_backend = "am4-tool-5070"
                    else:
                        resolved_backend = _val(rows, "default rung") or "omen-vllm"
                elif fam_name in ("tool_long_output",):
                    s5_ready = _val(rows, "facade alias am4-tool-5070 ready") is True and "am4-tool-5070" not in expected_absent
                    resolved_backend = "am4-tool-5070" if s5_ready else (_val(rows, "default rung") or "omen-vllm")
                elif fam_name in ("utility_text",):
                    resolved_backend = "fx99-vllm"
                else:
                    resolved_backend = _val(rows, "default rung") or "omen-vllm"

                if resolved_backend in expected_absent:
                    fail("routing-families-resolve-to-live-backends",
                         f"family {fam_name} resolves to absent backend {resolved_backend}",
                         "routing a family to an absent backend produces 500s or hangs (as happened on 2026-09-27)")
    return out


# --- render -------------------------------------------------------------------------------

def render_tables(rows: list[Row]) -> str:
    out = [BEGIN, ""]
    layers = sorted({r["layer"] for r in rows})
    for layer in layers:
        out.append(f"### {layer}\n")
        out.append("| setting | value | source | consumer | what it bounds | note |")
        out.append("|---|---|---|---|---|---|")
        for r in rows:
            if r["layer"] != layer:
                continue
            cells = [str(r["setting"]), f"`{r['value']}`" if r["value"] not in (None, "") else "—", f"`{r['source']}`" if r["source"] else "—",
                     r["consumer"] or "—", r["bounds"] or "—", r["note"] or ""]
            out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
        out.append("")
    viol = invariants(rows)
    out.append("### invariants\n")
    if viol:
        out.append("| rule | violation | earned by |"); out.append("|---|---|---|")
        for v in viol:
            out.append(f"| `{v['rule']}` | {v['detail'].replace('|', chr(92) + '|')} | {v['earned_by'].replace('|', chr(92) + '|')} |")
    else:
        out.append("All invariants hold.")
    out += ["", END]
    return "\n".join(out)


def render_into_doc(rows: list[Row]) -> bool:
    text = DOC.read_text(encoding="utf-8") if DOC.exists() else f"# Sizing map\n\n{BEGIN}\n{END}\n"
    if BEGIN not in text or END not in text:
        text = text.rstrip("\n") + f"\n\n{BEGIN}\n{END}\n"
    head, rest = text.split(BEGIN, 1); _, tail = rest.split(END, 1)
    new = head + render_tables(rows) + tail
    changed = new != text
    if changed:
        DOC.write_text(new, encoding="utf-8")
    return changed


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true"); ap.add_argument("--json", action="store_true")
    ap.add_argument("--render", action="store_true"); ap.add_argument("--live", action="store_true", help="read the running seats too")
    ap.add_argument("--no-measured", action="store_true", help="skip the execution-ledger aggregates")
    a = ap.parse_args(argv)
    # --render reads the seats too: their window and KV pool are stable across restarts of the same
    # config, and a changed config is exactly when the document should change.
    rows = collect(live=a.live or a.render, measured=not a.no_measured)
    if a.json:
        print(json.dumps({"schema": "sizing-map.v1", "rows": rows, "violations": invariants(rows)}, indent=2, default=str)); return 0
    if a.render:
        changed = render_into_doc(rows)
        print(f"{'rewrote' if changed else 'unchanged'} {DOC.relative_to(REPO)}")
    viol = invariants(rows)
    if a.check or not a.render:
        active_cfg = _val(rows, "active configuration")
        omen_p = _val(rows, "active omen profile")
        am4_p = _val(rows, "active am4 profile")
        if active_cfg and not str(active_cfg).startswith("unprobed"):
            print(f"configuration: {active_cfg} (omen={omen_p}, am4={am4_p})")
        for v in viol:
            print(f"VIOLATION {v['rule']}: {v['detail']}\n    earned by: {v['earned_by']}")
        print(f"{len(rows)} settings, {len(viol)} violation(s)")
        return 1 if viol else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
