#!/usr/bin/env python3
"""sizing_map — every context / KV / output / attempt / deadline number on this host, in one table,
with the invariants that tie them together.

The seat is the fact (vLLM's max_model_len, KV pool, max_num_seqs). backends-linux.toml declares
what the seat can serve; everything else derives from it. This tool reads all of those places,
prints them as one table, and checks the derivation rules, so docs/sizing-map.md cannot drift
from the files it describes.

    python tools/ops/sizing_map.py --check          exit 1 and name every violated invariant
    python tools/ops/sizing_map.py --json           the rows (sizing-map.v1), sorted, no clock
    python tools/ops/sizing_map.py --render         rewrite the generated block in docs/sizing-map.md (reads the live seats)
    python tools/ops/sizing_map.py --live           also read the running seats (/v1/models, /metrics)

Byte-stable: no timestamps, sorted rows, live values only when asked. Never prints a secret: the
seat key is read into the process for the two HTTP calls and nothing else.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tomllib
import urllib.request
from pathlib import Path
from typing import Any, Callable, Optional

REPO = Path(__file__).resolve().parents[2]
HOME = Path.home()
PROD = Path(os.environ.get("HEARTH_ROOT", str(HOME / "hearth-production")))
DOC = REPO / "docs" / "sizing-map.md"
BEGIN, END = "<!-- sizing-map:begin (generated by tools/ops/sizing_map.py; do not hand-edit) -->", "<!-- sizing-map:end -->"

Row = dict[str, Any]


def row(layer: str, setting: str, value: Any, source: str, consumer: str, bounds: str, note: str = "") -> Row:
    return {"layer": layer, "setting": setting, "value": value, "source": source, "consumer": consumer,
            "bounds": bounds, "note": note}


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n")
    except OSError:
        return ""


def _grep(text: str, pattern: str, group: int = 1, cast: Callable = str, default=None):
    m = re.search(pattern, text, re.MULTILINE)
    if not m:
        return default
    try:
        return cast(m.group(group))
    except (TypeError, ValueError):
        return default


def _line_of(path: Path, pattern: str) -> str:
    text = _read(path)
    for i, line in enumerate(text.splitlines(), 1):
        if re.search(pattern, line):
            return f"{_rel(path)}:{i}"
    return _rel(path)


def _rel(path: Path) -> str:
    p = str(path)
    for base, name in ((str(REPO), "repo"), (str(HOME), "~")):
        if p.startswith(base):
            return name + p[len(base):]
    return p


# --- collectors -------------------------------------------------------------------------------

def collect_seats(live: bool) -> list[Row]:
    rows: list[Row] = []
    script = HOME / "bin" / "start-vllm-seat.sh"
    stext = _read(script)
    defaults = {"OMEN_MAX_MODEL_LEN": _grep(stext, r"OMEN_MAX_MODEL_LEN:-(\d+)", cast=int, default=16384),
                "OMEN_MAX_NUM_SEQS": _grep(stext, r"OMEN_MAX_NUM_SEQS:-(\d+)", cast=int, default=16),
                "OMEN_GPU_MEM_UTIL": _grep(stext, r"OMEN_GPU_MEM_UTIL:-([0-9.]+)", cast=float, default=0.82)}
    for k, v in defaults.items():
        rows.append(row("seat", f"script default {k}", v, _line_of(script, k + ":-"), "vLLM (any seat without a drop-in)",
                        "context / sequences / VRAM fraction", "applies when no drop-in sets it"))
    key = None
    if live:
        for line in _read(HOME / ".config" / "omen-vllm" / "omen-api.env").splitlines():
            if line.startswith("VLLM_API_KEY="):
                key = line.split("=", 1)[1].strip().strip('"')
    for seat in (0, 1):
        unit = f"omen-vllm@{seat}"
        try:
            env = subprocess.run(["systemctl", "--user", "show", unit, "-p", "Environment", "--value"],
                                 capture_output=True, text=True, timeout=10).stdout.split()
        except (OSError, subprocess.TimeoutExpired):
            env = []
        eff = {}
        for item in env:
            if item.startswith("OMEN_") and "=" in item and not re.search(r"TOKEN|KEY", item, re.I):
                k, _, v = item.partition("="); eff[k] = v
        dropins = sorted(p.name for p in (HOME / ".config" / "systemd" / "user" / f"{unit}.service.d").glob("*.conf"))
        src = f"~/.config/systemd/user/{unit}.service.d/{{{','.join(dropins)}}}"
        served = eff.get("OMEN_SERVED_NAME") or (Path(eff["OMEN_MODEL"]).name + " (served name = checkpoint dir)" if eff.get("OMEN_MODEL") else "")
        rows.append(row("seat", f"{unit} served model", served, src, f"HAProxy :{18091 + seat}", "which checkpoint answers"))
        mml = int(eff.get("OMEN_MAX_MODEL_LEN") or defaults["OMEN_MAX_MODEL_LEN"])
        rows.append(row("seat", f"{unit} max_model_len", mml, src, "vLLM", "input + output tokens per request"))
        seqs = int(eff.get("OMEN_MAX_NUM_SEQS") or defaults["OMEN_MAX_NUM_SEQS"])
        rows.append(row("seat", f"{unit} max_num_seqs", seqs, src if eff.get("OMEN_MAX_NUM_SEQS") else _line_of(script, "OMEN_MAX_NUM_SEQS:-"),
                        "vLLM scheduler", "concurrent sequences admitted", "" if eff.get("OMEN_MAX_NUM_SEQS") else "script default; no drop-in sets it"))
        rows.append(row("seat", f"{unit} gpu_memory_utilization", float(eff.get("OMEN_GPU_MEM_UTIL") or defaults["OMEN_GPU_MEM_UTIL"]), src, "vLLM", "VRAM fraction (weights + KV)"))
        if eff.get("OMEN_KV_CACHE_BYTES"):
            rows.append(row("seat", f"{unit} kv_cache_memory_bytes", int(eff["OMEN_KV_CACHE_BYTES"]), src, "vLLM", "fixed KV pool (overrides the utilisation for KV)"))
        for k, label in (("OMEN_MAX_BATCHED_TOKENS", "max_num_batched_tokens"), ("OMEN_PREFIX_MATCH_UNIT", "prefix_match_unit"), ("OMEN_MTP_K", "mtp_k")):
            if eff.get(k):
                rows.append(row("seat", f"{unit} {label}", int(eff[k]), src, "vLLM", {"max_num_batched_tokens": "prefill chunk", "prefix_match_unit": "prefix-hit granularity", "mtp_k": "speculative tokens"}[label]))
        # stale-comment and duplicate-key detectors on the drop-ins
        setters: dict[str, list[str]] = {}
        for name in dropins:
            text = _read(HOME / ".config" / "systemd" / "user" / f"{unit}.service.d" / name)
            for k in re.findall(r'^Environment="?(OMEN_[A-Z_]+)=', text, re.M):
                setters.setdefault(k, []).append(name)
            if re.search(r"staged", text, re.I) and name.endswith(".conf"):
                rows.append(row("seat", f"{unit} {name} says 'staged'", True, f"~/.config/systemd/user/{unit}.service.d/{name}", "operator", "misleading comment on an ACTIVE drop-in"))
        for k, names in sorted(setters.items()):
            if len(names) > 1:
                rows.append(row("seat", f"{unit} {k} set by {len(names)} drop-ins", " < ".join(names), f"~/.config/systemd/user/{unit}.service.d/", "systemd (last wins, alphabetical)", "the earlier file is dead configuration"))
        if live and key:
            try:
                req = urllib.request.Request(f"http://127.0.0.1:{18091 + seat}/v1/models", headers={"Authorization": f"Bearer {key}"})
                with urllib.request.urlopen(req, timeout=5) as r:
                    data = json.load(r)["data"]
                for m in data:
                    rows.append(row("seat-live", f"{unit} /v1/models", f"{m['id']} max_model_len={m.get('max_model_len')}", f"http://127.0.0.1:{18091 + seat}/v1/models", "clients", "live window"))
                req = urllib.request.Request(f"http://127.0.0.1:{18091 + seat}/metrics", headers={"Authorization": f"Bearer {key}"})
                with urllib.request.urlopen(req, timeout=5) as r:
                    metrics = r.read().decode("utf-8", "replace")
                m = re.search(r'^vllm:cache_config_info\{([^}]*)\}', metrics, re.M)
                if m:
                    labels = dict(re.findall(r'(\w+)="([^"]*)"', m.group(1)))
                    for k in ("kv_cache_size_tokens", "kv_cache_max_concurrency", "block_size", "cache_dtype"):
                        if k in labels:
                            v = labels[k]
                            v = int(v) if v.isdigit() else (round(float(v), 2) if re.fullmatch(r"[0-9.]+", v) else v)
                            rows.append(row("seat-live", f"{unit} {k}", v, f"http://127.0.0.1:{18091 + seat}/metrics cache_config_info", "vLLM", "KV pool" if "kv" in k else "block / dtype"))
            except Exception as exc:  # noqa: BLE001 -- live is best-effort
                rows.append(row("seat-live", f"{unit} live read", f"unavailable: {type(exc).__name__}", "", "", ""))
    return rows


def collect_router() -> list[Row]:
    path = HOME / ".config" / "omen-vllm" / "haproxy.cfg"
    text = _read(path)
    rows = [row("router", "haproxy global maxconn", _grep(text, r"^\s*maxconn\s+(\d+)", cast=int), _line_of(path, r"^\s*maxconn"), "haproxy", "total open connections")]
    for t in ("connect", "client", "server", "queue"):
        v = _grep(text, rf"^\s*timeout {t}\s+(\d+)s", cast=int)
        rows.append(row("router", f"haproxy timeout {t}", v, _line_of(path, rf"timeout {t}") if v is not None else _rel(path), "haproxy",
                        {"connect": "backend connect", "client": "idle per request (client side)", "server": "idle per request (seat side)", "queue": "wait for a free server slot"}[t],
                        "" if v is not None else "not set"))
    for fe, port in re.findall(r"frontend (\w+)\n\s+bind 127\.0\.0\.1:(\d+)", text):
        rows.append(row("router", f"frontend {fe}", int(port), _line_of(path, f"frontend {fe}"), "HEARTH rung endpoint", "which lane a port is"))
    for be, body in re.findall(r"backend (\w+)\n((?:\s+.*\n)+)", text):
        servers = re.findall(r"server (\w+) 127\.0\.0\.1:(\d+)([^\n]*)", body)
        for name, port, rest in servers:
            mc = _grep(rest, r"maxconn (\d+)", cast=int)
            rows.append(row("router", f"backend {be} server {name}", f"127.0.0.1:{port}" + (f" maxconn {mc}" if mc else " (no maxconn)"), _line_of(path, f"server {name}"), "haproxy", "seat behind the lane; per-server maxconn queues overflow at the router", "" if mc else "no per-server maxconn: overflow queues inside vLLM"))
    return rows


def _toml(path: Path) -> dict:
    try:
        return tomllib.loads(_read(path))
    except (tomllib.TOMLDecodeError, OSError):
        return {}


def collect_backends() -> list[Row]:
    path = Path(os.environ.get("HEARTH_BACKENDS", str(PROD / "backends-linux.toml")))
    doc = _toml(path)
    rows = [row("rung", "default rung", doc.get("default"), _line_of(path, "^default"), "local_generate", "where untagged calls land")]
    for b in doc.get("backend", []):
        s = b.get("settings", {})
        name = b["name"]
        for k, bounds in (("context_tokens", "input + output tokens the seat holds"), ("context_bytes", "payload bytes admitted by the door (3.5 B/token, no output reserve)"),
                          ("max_tokens", "default output budget = the reserve local-work subtracts"), ("timeout_s", "HTTP timeout when the caller sets none (execution path always overrides)"),
                          ("parallel_slots", "HEARTH lease slots on this rung")):
            if k in s:
                rows.append(row("rung", f"{name} {k}", s[k], _line_of(path, rf"^\s*{k}\s*=") , "backends pool", bounds))
        rows.append(row("rung", f"{name} endpoint", b.get("endpoint"), _line_of(path, f'name = "{name}"'), "door", "which router port"))
    text = _read(path)
    m = re.search(r"KV pool[^\n]*?(\d{2},\d{3}|\d{5})[^\n]*tokens", text)
    if m:
        rows.append(row("rung", "backends-linux.toml KV-pool comment", m.group(1).replace(",", ""), _line_of(path, r"KV pool"), "operator", "documentation of the dense seat's KV pool", "compared against the live kv_cache_size_tokens under --live"))
    return rows


def collect_routes_and_families() -> list[Row]:
    rows: list[Row] = []
    rp = Path(os.environ.get("HEARTH_LOCAL_WORK_ROUTES", str(PROD / "local-work-routes-linux.toml")))
    for lane, spec in _toml(rp).get("lane", {}).items():
        rows.append(row("local-work", f"lane {lane}", spec.get("backend"), _line_of(rp, rf"\[lane\.{lane}\]"), "submit_local_work", "which rung a lane is"))
    fp = Path(os.environ.get("HEARTH_ROUTING_FAMILIES", str(PROD / "routing-families-linux.toml")))
    fam = _toml(fp).get("family", {})
    for name, spec in sorted(fam.items()):
        d = spec.get("depth_override") or {}
        val = f"{spec.get('model_id')}"
        if d.get("min_prompt_tokens"):
            val += f"; >= {d['min_prompt_tokens']} prompt tokens -> {d.get('model_id')}"
        if spec.get("min_prompt_tokens"):
            val += f"; >= {spec['min_prompt_tokens']} -> {spec.get('model_id')} else {spec.get('below_threshold_model_id')}"
        if spec.get("tags"):
            val += f"; tags {spec['tags']}"
        rows.append(row("family", f"family {name}", val, _line_of(fp, rf"\[family\.{name}\]"), "families.recommend (advisory) / local_generate tag route", "model + depth threshold (prompt tokens = payload bytes // 4)"))
    return rows


def collect_operations() -> list[Row]:
    path = Path(os.environ.get("HEARTH_OPERATIONS", str(REPO / "hearth" / "etc" / "operations.toml")))
    doc = _toml(path)
    rows = []
    for op, spec in doc.get("operation", {}).items():
        if op not in ("llm.chat", "inference.generate", "work.produce"):
            continue
        for k, bounds in (("max_tokens_ceiling", "largest output budget a job may ask for"), ("deadline_ceiling_s", "largest deadline; also the default when none is given"), ("max_prompt_bytes", "largest prompt")):
            rows.append(row("operation", f"{op} {k}", spec.get(k), _line_of(path, rf'\[operation\."{re.escape(op)}"\]'), "execution policy_for", bounds))
    return rows


def collect_door_code() -> list[Row]:
    rows = []
    inf = REPO / "hearth" / "toolsurface" / "inference.py"; t = _read(inf)
    rows.append(row("door", "local_generate default max_tokens (no rung value)", _grep(t, r"rmt = int\(setting\) if setting is not None else (\d+)", cast=int), _line_of(inf, r"else 1024"), "local_generate", "output when neither caller nor rung says"))
    rows.append(row("door", "local_generate DEFAULT_TIMEOUT_S", _grep(t, r"^DEFAULT_TIMEOUT_S = (\d+)", cast=int), _line_of(inf, "^DEFAULT_TIMEOUT_S"), "local_generate", "HTTP timeout when neither caller nor rung says", "never used on the execution path: it passes deadline - now"))
    rows.append(row("door", "files= per-file / total cap (bytes)", f"{_grep(t, r'^FILES_PER_FILE_CAP = (.+)$')} / {_grep(t, r'^FILES_TOTAL_CAP = (.+)$')}", _line_of(inf, "^FILES_PER_FILE_CAP"), "_pack_files", "packed file bytes", "unreachable on Linux: every rung's context_bytes is smaller"))
    rows.append(row("door", "family depth estimate", "payload_bytes // 4", _line_of(inf, r"// 4"), "families.recommend", "prompt_tokens for depth rules"))
    be = REPO / "hearth" / "toolsurface" / "backends.py"
    if "_output_reserve_rejection" in _read(be):
        rows.append(row("door", "payload admission rule (pin and tag route)", "payload_bytes <= context_bytes AND payload_bytes // 4 + max_tokens <= context_tokens", _line_of(be, r"def _output_reserve_rejection"), "select_backend", "admission", "reserve = caller max_tokens else the rung's"))
    else:
        rows.append(row("door", "payload admission rule (pin and tag route)", "payload_bytes <= context_bytes", _line_of(be, r"payload_bytes > pinned_context"), "select_backend", "admission", "reserves no output tokens"))
    lw = REPO / "hearth" / "localwork" / "service.py"; t = _read(lw)
    rows.append(row("local-work", "auto lane floor (evidence tokens -> deep)", _grep(t, r"floor = (\d+) if task_family == \"quote_retrieval\" else (\d+)", group=2, cast=int), _line_of(lw, r"floor = 4096"), "_lane", "fast vs deep", f"quote_retrieval floor {_grep(t, r'floor = (\d+) if', cast=int)}; evidence = source pack only, counted with the fast lane's tokenizer"))
    rows.append(row("local-work", "output_reserve fallback", _grep(t, r'settings.get\("max_tokens"\) or (\d+)', cast=int), _line_of(lw, r"output_reserve ="), "submit", "reserve when the rung declares none"))
    rows.append(row("local-work", "exact context check", "input_tokens + output_reserve <= context_tokens", _line_of(lw, r"input_tokens \+ output_reserve"), "submit", "refuses at submit"))
    rows.append(row("local-work", "tokenizer / git / apply timeouts (s)", f"{_grep(t, r'_server_token_count.*?timeout=(\d+)', cast=int) or 30} / 120 / 120", _line_of(lw, r"timeout=120"), "submit, validation", "submit latency; candidate validation"))
    tl = REPO / "hearth" / "toolsurface" / "local_work.py"; t = _read(tl)
    rows.append(row("local-work", "submit_local_work deadline_s default", _grep(t, r"deadline_s: int = (\d+)", cast=int), _line_of(tl, r"deadline_s: int ="), "MCP tool", "job deadline when the caller sets none"))
    ex = REPO / "hearth" / "execution" / "service.py"; t = _read(ex)
    rows.append(row("execution", "workers / max_pending", f"{_grep(t, r'workers: int = (\d+)', cast=int)} / {_grep(t, r'max_pending: int = (\d+)', cast=int)}", _line_of(ex, r"workers: int ="), "executor", "concurrent jobs / queue depth"))
    rows.append(row("execution", "parallel_slots clamp", "1..128", _line_of(ex, r"min\(value, 128\)"), "lease limit", "per-rung concurrency"))
    rows.append(row("execution", "provider HTTP timeout", "max(1, deadline - now)", _line_of(ex, r"int\(deadline - time.monotonic\(\)\)"), "_run_job", "the '1199'", "queue wait counts against the deadline"))
    on = REPO / "hearth" / "scheduler" / "ontology.py"; t = _read(on)
    rows.append(row("scheduler", "default inference duration (s)", _grep(t, r'"inference": ([0-9.]+)', cast=float), _line_of(on, r'"inference":'), "propose_schedule (advisory)", "job length estimate when capacity.json has no bucket"))
    return rows


def collect_lanes() -> list[Row]:
    rows = []
    bf = REPO / "fleet" / "bankedfire_linux.py"; t = _read(bf)
    rows.append(row("drain", "BANKEDFIRE_SLOTS default", _grep(t, r'"BANKEDFIRE_SLOTS", "([^"]+)"'), _line_of(bf, "BANKEDFIRE_SLOTS"), "bankedfire_linux.tick", "unattended in-flight work per lane", f"env now: {os.environ.get('BANKEDFIRE_SLOTS', '(unset)')}"))
    rows.append(row("drain", "brief deadline_s default", _grep(t, r'"deadline_s": int\(fields.get\("deadline_s", (\d+)\)\)', cast=int), _line_of(bf, r'fields.get\("deadline_s"'), "submit_args_from_brief", "local-work job deadline"))
    rows.append(row("drain", "proofing max_tokens / deadline_s", f"{_grep(t, r'\"task_family\": \"drafting\", \"max_tokens\": (\d+)', cast=int)} / {_grep(t, r'\"deadline_s\": (\d+), \"idempotency_key\"', cast=int)}", _line_of(bf, r'"task_family": "drafting"'), "proofing_args_from_brief", "proposal output / deadline"))
    rows.append(row("drain", "door MCP client timeout (s)", _grep(t, r"timeout=(\d+)\) as \(r, w, _\)", cast=int), _line_of(bf, r"streamablehttp_client"), "call_tool", "submit / status calls"))
    rows.append(row("drain", "systemd-run launch timeout (s)", _grep(t, r"subprocess.run\(argv, capture_output=True, text=True, timeout=(\d+)\)", cast=int), _line_of(bf, r"systemd-run"), "experiment / deepagents launch", ""))
    rows.append(row("drain", "skip backoff (days)", _grep(t, r"^SKIP_DAYS = (\d+)", cast=int), _line_of(bf, "^SKIP_DAYS"), "candidate_exclusions", "failed candidate retry"))
    timer = HOME / ".config" / "systemd" / "user" / "bankedfire-drain.timer"
    rows.append(row("drain", "tick interval", _grep(_read(timer), r"OnUnitActiveSec=(\S+)"), _rel(timer), "systemd", "how often the night loop looks"))
    pr = REPO / "fleet" / "presence_linux.py"
    rows.append(row("drain", "PRESENCE idle minutes", _grep(_read(pr), r"^DEFAULT_IDLE_MIN = (\d+)", cast=int), _line_of(pr, "^DEFAULT_IDLE_MIN"), "presence.report", "away threshold", f"env now: {os.environ.get('PRESENCE_IDLE_MIN', '(unset)')}"))
    ex = REPO / "fleet" / "experiment_linux.py"; t = _read(ex)
    rows.append(row("experiment", "RESTORE_MARGIN_MIN / DEFAULT_MAX_MINUTES / DEFAULT_RESTORE_BY", f"{_grep(t, r'^RESTORE_MARGIN_MIN = (\d+)')} / {_grep(t, r'^DEFAULT_MAX_MINUTES = (\d+)')} / {_grep(t, r'^DEFAULT_RESTORE_BY = \"([^\"]+)\"')}", _line_of(ex, "^RESTORE_MARGIN_MIN"), "Experiment.campaign_budget_s", "campaign wall clock"))
    rows.append(row("experiment", "seat wait (s)", _grep(t, r'str\(self.seat\), "(\d+)"', cast=int), _line_of(ex, r"WAIT_SCRIPT\), str\(self.seat\)"), "restart_and_wait", "seat restart"))
    da = REPO / "fleet" / "deepagents_linux.py"
    rows.append(row("deepagents-lane", "RUN_TIMEOUT_S (wrapper)", _grep(_read(da), r"^RUN_TIMEOUT_S = (\d+)", cast=int), _line_of(da, "^RUN_TIMEOUT_S"), "Delivery.run", "outer subprocess timeout"))
    ws = HOME / "bin" / "wait-vllm-seat.sh"
    rows.append(row("seat", "wait-vllm-seat default max (s)", _grep(_read(ws), r"max=\$\{2:-(\d+)\}", cast=int), _line_of(ws, r"max=\$\{2:-"), "operator, experiment lane", "seat startup wait"))
    mr = REPO / "tools" / "hearth-morning-report"
    rows.append(row("report", "morning report git/apply timeouts (s)", sorted({int(x) for x in re.findall(r"timeout=(\d+)\)", _read(mr))}), _line_of(mr, r"timeout=60"), "hearth-morning-report", "apply-check per candidate"))
    return rows


def collect_runner() -> list[Row]:
    rows = []
    root = Path(os.environ.get("DEEPAGENTS_LINUX", str(HOME / "work" / "deepagents-linux")))
    rl = root / "run_linux_delivery.py"; t = _read(rl)
    for name, ctx in re.findall(r'"(\w[\w-]*)": \{"model": "[^"]+", "endpoint": "[^"]+",\s*"token_env": "\w+", "context": (\d+)', t):
        rows.append(row("runner", f"ROUTES.{name}.context", int(ctx), _line_of(rl, f'"{name}": \\{{"model"'), "AccountedTransport context check, summarization trigger", "prompt + output + 32 <= context"))
    rows.append(row("runner", "output_limit report / code", f"{_grep(t, r'output_limit = (\d+) if args.report else (\d+)', group=1)} / {_grep(t, r'output_limit = (\d+) if args.report else (\d+)', group=2)}", _line_of(rl, r"output_limit = "), "PinnedChat max_tokens", "output tokens per model call"))
    rows.append(row("runner", "RequestBudget limit (attempts)", _grep(t, r"RequestBudget\(deadline=time.time\(\) \+ \d+, limit=(\d+)\)", cast=int), _line_of(rl, r"RequestBudget\("), "AccountedTransport.dispatch", "physical inference calls per run"))
    rows.append(row("runner", "RequestBudget deadline (s)", _grep(t, r"RequestBudget\(deadline=time.time\(\) \+ (\d+)", cast=int), _line_of(rl, r"RequestBudget\("), "AccountedTransport", "run wall clock"))
    rows.append(row("runner", "tool_token_limit_before_evict", _grep(t, r"tool_token_limit_before_evict=(\d+)", cast=int), _line_of(rl, "tool_token_limit_before_evict"), "EvictingFilesystem", "tool result size before it is moved to /large_tool_results (4 chars/token)"))
    rows.append(row("runner", "recursion_limit", _grep(t, r'"recursion_limit": (\d+)', cast=int), _line_of(rl, "recursion_limit"), "LangGraph invoke", "graph supersteps (~2 per model turn)"))
    rows.append(row("runner", "httpx / PinnedChat timeout (s)", _grep(t, r"timeout=(\d+), trust_env", cast=int), _line_of(rl, r"httpx.Client"), "per request", ""))
    rows.append(row("runner", "default --backend", _grep(t, r'choices=tuple\(ROUTES\), default="([^"]+)"'), _line_of(rl, r'default="omen"'), "CLI", "route when the wrapper passes none"))
    at = root / "poc" / "accounted_transport.py"; t = _read(at)
    rows.append(row("runner", "RequestBudget default limit", _grep(t, r"def __init__\(self, \*, deadline, limit=(\d+)\)", cast=int), _line_of(at, r"limit=32"), "any caller that omits limit", "attempts"))
    rows.append(row("runner", "transport output guard", f"reads {re.search(r'payload.get\(\"(\w+)\", payload.get\(\"(\w+)\", (\d+)\)\)', t).groups() if re.search(r'payload.get\(\"(\w+)\", payload.get\(\"(\w+)\", (\d+)\)\)', t) else '?'}; requires 0 < output <= {_grep(t, r'0 < output <= (\d+)', cast=int)}", _line_of(at, r"0 < output <="), "handle_request", "output cap per call", "langchain sends max_completion_tokens, so the guard sees the default"))
    return rows


def collect_clients() -> list[Row]:
    rows = []
    cx = HOME / ".codex" / "config.toml"; t = _read(cx)
    rows.append(row("client", "codex mcp tool_timeout_sec", _grep(t, r"^tool_timeout_sec = (\d+)", cast=int), _line_of(cx, "^tool_timeout_sec"), "Codex", "longest door call"))
    try:
        cj = json.loads(_read(HOME / ".claude.json"))
        rows.append(row("client", "claude code hearth timeout (ms)", cj["mcpServers"]["hearth"].get("timeout"), "~/.claude.json mcpServers.hearth.timeout", "Claude Code", "longest door call"))
    except Exception:  # noqa: BLE001
        pass
    return rows


def collect_measured() -> list[Row]:
    """p90 of the dense lane's work.produce runs from the execution ledger (aggregates only)."""
    path = PROD / "var" / "execution" / "events.ndjson"
    outs, durs = [], []
    try:
        with path.open("rb") as fh:
            for raw in fh:
                if b'"invocation.succeeded"' not in raw or b'"work.produce"' not in raw and b'omen-dense-27b' not in raw:
                    continue
                try:
                    e = json.loads(raw)
                except ValueError:
                    continue
                if e.get("event_type") != "invocation.succeeded":
                    continue
                o = e.get("observed") or {}
                if o.get("backend") != "omen-dense-27b":
                    continue
                if o.get("tokens_out") and o.get("duration_ms"):
                    outs.append(int(o["tokens_out"])); durs.append(int(o["duration_ms"]))
    except OSError:
        return []
    if not outs:
        return []
    rate = [1000.0 * o / d for o, d in zip(outs, durs) if d]
    rate.sort(); outs.sort(); durs.sort()
    p90 = lambda xs: xs[min(len(xs) - 1, int(0.9 * (len(xs) - 1)))]  # noqa: E731
    return [row("measured", "omen-dense-27b invocations (n)", len(outs), _rel(path), "sizing rules", "sample"),
            row("measured", "omen-dense-27b tokens_out p90 / max", f"{p90(outs)} / {outs[-1]}", _rel(path), "", "how close outputs come to the cap"),
            row("measured", "omen-dense-27b duration_ms p90 / max", f"{p90(durs)} / {durs[-1]}", _rel(path), "", "how close jobs come to the deadline"),
            row("measured", "omen-dense-27b decode tok/s median", round(rate[len(rate) // 2], 1), _rel(path), "deadline derivation", "output / duration (prefill included, so a floor)")]


def collect(live: bool, measured: bool) -> list[Row]:
    rows: list[Row] = []
    for fn in (collect_seats, collect_router, collect_backends, collect_routes_and_families, collect_operations,
               collect_door_code, collect_lanes, collect_runner, collect_clients):
        rows.extend(fn(live) if fn is collect_seats else fn())
    if measured:
        rows.extend(collect_measured())
    return sorted(rows, key=lambda r: (r["layer"], r["setting"]))


# --- invariants -------------------------------------------------------------------------------

def _val(rows: list[Row], setting: str, default=None):
    for r in rows:
        if r["setting"] == setting:
            return r["value"]
    return default


def _num(v, default=None):
    try:
        return float(v)
    except (TypeError, ValueError):
        return default


def invariants(rows: list[Row]) -> list[dict]:
    """Each rule cites the observation that earned it. Returns the violations."""
    out: list[dict] = []
    def fail(rule: str, detail: str, earned_by: str):
        out.append({"rule": rule, "detail": detail, "earned_by": earned_by})
    rungs = {}
    for r in rows:
        if r["layer"] == "rung" and " " in r["setting"]:
            name, key = r["setting"].split(" ", 1); rungs.setdefault(name, {})[key] = r["value"]
    seat_for = {"omen-vllm": "omen-vllm@1", "omen-dense-27b": "omen-vllm@0"}
    # 1. rung context == seat window
    for rung, seat in seat_for.items():
        s = rungs.get(rung, {}); mml = _val(rows, f"{seat} max_model_len")
        if s.get("context_tokens") is not None and mml is not None and int(s["context_tokens"]) != int(mml):
            fail("rung-context-equals-seat-window", f"{rung} context_tokens {s['context_tokens']} != {seat} max_model_len {mml}", "the 30B seat refused 65536 at startup (07-serving-recipe.md); the declaration must be the seat's")
    # 2. max_num_seqs >= parallel_slots and slots x typical <= KV
    for rung, seat in seat_for.items():
        s = rungs.get(rung, {}); seqs = _num(_val(rows, f"{seat} max_num_seqs")); slots = _num(s.get("parallel_slots"))
        if seqs is not None and slots is not None and seqs < slots:
            fail("seat-admits-at-least-the-leases", f"{seat} max_num_seqs {seqs:g} < {rung} parallel_slots {slots:g}", "leases would queue on a seat that cannot admit them")
        kv = _num(_val(rows, f"{seat} kv_cache_size_tokens"))
        if kv is not None and slots is not None and s.get("context_tokens") is not None and s.get("max_tokens") is not None:
            # A realistic concurrent request: measured p90 input on the dense lane was 19.5K of a
            # 65,536 window (0.30) and p90 output 5.7K of a 16,384 reserve; half the reserve is the
            # conservative allowance. vLLM preempts when the pool is exhausted, so the sum must fit.
            typical = 0.30 * float(s["context_tokens"]) + 0.5 * float(s["max_tokens"])
            if slots * typical > kv:
                fail("slots-fit-the-kv-pool", f"{rung}: {slots:g} slots x typical {typical:.0f} tokens = {slots * typical:.0f} > {seat} KV pool {kv:.0f}", "a work.produce waited 9.3 s for a slot on 2026-09-27 at 3 slots; preemption follows oversubscription")
    # 3. operation ceilings vs rungs
    ceil = {}
    for r in rows:
        if r["layer"] == "operation" and r["setting"].endswith(" max_tokens_ceiling"):
            ceil[r["setting"].split(" ")[0]] = _num(r["value"])
    max_reserve = max((_num(s.get("max_tokens"), 0) for s in rungs.values()), default=0)
    for op, c in ceil.items():
        if c and max_reserve and c > max_reserve:
            fail("operation-ceiling-within-the-largest-rung-reserve", f"{op} max_tokens_ceiling {c:g} > largest rung max_tokens {max_reserve:g}", "a rung's max_tokens is what its seat is declared to serve as output; an operation that allows more admits a request no seat can complete (a 32,768 output on the 40,960 seat leaves 8K for input)")
    wp = ceil.get("work.produce")
    dense = rungs.get("omen-dense-27b", {})
    if wp and dense.get("max_tokens") is not None and _num(dense["max_tokens"]) > wp:
        fail("rung-reserve-within-ceiling", f"omen-dense-27b max_tokens {dense['max_tokens']} > work.produce ceiling {wp:g}", "a submit at the rung's own default would be refused at the ceiling")
    # 4. admission reserves output
    if _val(rows, "payload admission rule (pin and tag route)") == "payload_bytes <= context_bytes":
        fail("door-admission-reserves-output", "local_generate admits payload <= context_bytes and reserves nothing for max_tokens", "the pinned-rung refusal exists to fail at the door, not the server; today a full payload plus the default output overflows omen-vllm (40,960 + 8,192), am4 (16,384 + 8,192) and fx99 (4,096 + 2,048)")
    # 5. deadlines and timeouts chain
    dl = _num(_val(rows, "work.produce deadline_ceiling_s")); rate = _num(_val(rows, "omen-dense-27b decode tok/s median"))
    if dl and wp and rate:
        need = wp / rate + 60
        if need > dl:
            fail("deadline-covers-the-output", f"work.produce ceiling {wp:g} tokens at {rate:g} tok/s needs ~{need:.0f} s > deadline_ceiling_s {dl:g}", "the 5,690-token candidate took 545 s on 2026-09-27; a full 8,192 needs ~790 s + prefill")
    sub_dl = _num(_val(rows, "submit_local_work deadline_s default"))
    if sub_dl and dl and sub_dl < dl:
        pass  # a lower default than the ceiling is allowed; recorded in the table
    for who, key, scale in (("haproxy timeout server", "haproxy timeout server", 1), ("codex mcp tool_timeout_sec", "codex mcp tool_timeout_sec", 1), ("claude code hearth timeout (ms)", "claude code hearth timeout (ms)", 1000)):
        v = _num(_val(rows, key))
        if v is not None and dl and v / scale < dl:
            fail("client-timeouts-cover-the-deadline", f"{who} {v:g}{'ms' if scale == 1000 else 's'} < deadline_ceiling_s {dl:g}", "a door call that outlives its client timeout is reported as a client error, not a result")
    if _val(rows, "haproxy timeout queue") is None:
        fail("router-queues-overflow", "haproxy has no per-server maxconn and no timeout queue", "with max_num_seqs 16 on both seats, the 17th request waits inside vLLM with no router-side bound")
    # 6. runner budgets vs route
    for name, rung in (("omen", "omen-vllm"), ("omen-dense", "omen-dense-27b")):
        rc = _num(_val(rows, f"ROUTES.{name}.context")); sc = _num(rungs.get(rung, {}).get("context_tokens"))
        if rc is not None and sc is not None and rc != sc:
            fail("runner-context-equals-seat", f"ROUTES.{name}.context {rc:g} != {rung} context_tokens {sc:g}", "the runner's own context check and summarization trigger use this number")
    rd = _num(_val(rows, "RequestBudget deadline (s)")); wt = _num(_val(rows, "RUN_TIMEOUT_S (wrapper)"))
    if rd and wt and wt < rd + 60:
        fail("wrapper-outlives-the-runner", f"RUN_TIMEOUT_S {wt:g} < runner deadline {rd:g} + 60", "a wrapper that kills first leaves no result.json")
    ev = _num(_val(rows, "tool_token_limit_before_evict")); dctx = _num(_val(rows, "ROUTES.omen-dense.context"))
    if ev is not None and dctx and ev < dctx / 16:
        fail("eviction-scales-with-context", f"tool_token_limit_before_evict {ev:g} < ROUTES.omen-dense.context / 16 ({dctx / 16:.0f})", "2026-09-27 retry: a 1,500-token preview cap on a 65K lane produced 12 read-only calls and 5 evicted files, and the attempt budget ran out")
    guard = str(_val(rows, "transport output guard", ""))
    if "max_completion_tokens" not in guard:
        fail("guard-reads-the-field-langchain-sends", f"transport output guard {guard}", "measured 2026-09-27: every request carried max_completion_tokens=3072 and the guard checked a default 2048")
    # 7. stale comments
    for r in rows:
        if r["setting"].endswith("says 'staged'") and r["value"] is True:
            fail("active-drop-in-says-staged", r["source"], "an operator reading the drop-in dir cannot tell what is live")
        if " set by " in r["setting"] and "drop-ins" in r["setting"]:
            fail("one-drop-in-per-key", f"{r['setting']}: {r['value']}", "seat 0's max-model-len.conf (40960) is overridden by stage2-27b-mtp.conf (65536); its comment describes the other checkpoint")
    kv_comment = _num(_val(rows, "backends-linux.toml KV-pool comment")); kv_live = _num(_val(rows, "omen-vllm@0 kv_cache_size_tokens"))
    if kv_comment and kv_live and abs(kv_comment - kv_live) > 0.25 * kv_live:
        fail("kv-comment-matches-live", f"backends-linux.toml says KV pool {kv_comment:.0f}; live seat 0 reports {kv_live:.0f}", "the pool varies per start (76,706 and 99,048 seen on the same config, 2026-09-27); the comment must say so and stay within 25%")
    return out


# --- render -------------------------------------------------------------------------------

def render_tables(rows: list[Row]) -> str:
    out = [BEGIN, ""]
    layers = sorted({r["layer"] for r in rows})
    for layer in layers:
        out.append(f"### {layer}\n")
        out.append("| setting | value | source | consumer | what it bounds | note |")
        out.append("|---|---|---|---|---|---|")
        for r in rows:
            if r["layer"] != layer:
                continue
            cells = [str(r["setting"]), f"`{r['value']}`" if r["value"] not in (None, "") else "—", f"`{r['source']}`" if r["source"] else "—",
                     r["consumer"] or "—", r["bounds"] or "—", r["note"] or ""]
            out.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
        out.append("")
    viol = invariants(rows)
    out.append("### invariants\n")
    if viol:
        out.append("| rule | violation | earned by |"); out.append("|---|---|---|")
        for v in viol:
            out.append(f"| `{v['rule']}` | {v['detail'].replace('|', chr(92) + '|')} | {v['earned_by'].replace('|', chr(92) + '|')} |")
    else:
        out.append("All invariants hold.")
    out += ["", END]
    return "\n".join(out)


def render_into_doc(rows: list[Row]) -> bool:
    text = DOC.read_text(encoding="utf-8") if DOC.exists() else f"# Sizing map\n\n{BEGIN}\n{END}\n"
    if BEGIN not in text or END not in text:
        text = text.rstrip("\n") + f"\n\n{BEGIN}\n{END}\n"
    head, rest = text.split(BEGIN, 1); _, tail = rest.split(END, 1)
    new = head + render_tables(rows) + tail
    changed = new != text
    if changed:
        DOC.write_text(new, encoding="utf-8")
    return changed


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true"); ap.add_argument("--json", action="store_true")
    ap.add_argument("--render", action="store_true"); ap.add_argument("--live", action="store_true", help="read the running seats too")
    ap.add_argument("--no-measured", action="store_true", help="skip the execution-ledger aggregates")
    a = ap.parse_args(argv)
    # --render reads the seats too: their window and KV pool are stable across restarts of the same
    # config, and a changed config is exactly when the document should change.
    rows = collect(live=a.live or a.render, measured=not a.no_measured)
    if a.json:
        print(json.dumps({"schema": "sizing-map.v1", "rows": rows, "violations": invariants(rows)}, indent=2, default=str)); return 0
    if a.render:
        changed = render_into_doc(rows)
        print(f"{'rewrote' if changed else 'unchanged'} {DOC.relative_to(REPO)}")
    viol = invariants(rows)
    if a.check or not a.render:
        for v in viol:
            print(f"VIOLATION {v['rule']}: {v['detail']}\n    earned by: {v['earned_by']}")
        print(f"{len(rows)} settings, {len(viol)} violation(s)")
        return 1 if viol else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
